// Code generated by ogen, DO NOT EDIT.
package management_api

type AddAPIApplicationScopeRes interface {
	addAPIApplicationScopeRes()
}

type AddAPIScopeRes interface {
	addAPIScopeRes()
}

type AddAPIsRes interface {
	addAPIsRes()
}

type AddLogoRes interface {
	addLogoRes()
}

type AddLogoutRedirectURLsRes interface {
	addLogoutRedirectURLsRes()
}

type AddOrganizationLogoRes interface {
	addOrganizationLogoRes()
}

type AddOrganizationUserAPIScopeRes interface {
	addOrganizationUserAPIScopeRes()
}

type AddOrganizationUsersRes interface {
	addOrganizationUsersRes()
}

type AddRedirectCallbackURLsRes interface {
	addRedirectCallbackURLsRes()
}

type AddRoleScopeRes interface {
	addRoleScopeRes()
}

type CreateApplicationRes interface {
	createApplicationRes()
}

type CreateBillingAgreementRes interface {
	createBillingAgreementRes()
}

type CreateCategoryRes interface {
	createCategoryRes()
}

type CreateConnectionRes interface {
	createConnectionRes()
}

type CreateEnvironmentVariableRes interface {
	createEnvironmentVariableRes()
}

type CreateFeatureFlagRes interface {
	createFeatureFlagRes()
}

type CreateMeterUsageRecordRes interface {
	createMeterUsageRecordRes()
}

type CreateOrganizationRes interface {
	createOrganizationRes()
}

type CreateOrganizationUserPermissionRes interface {
	createOrganizationUserPermissionRes()
}

type CreateOrganizationUserRoleRes interface {
	createOrganizationUserRoleRes()
}

type CreatePermissionRes interface {
	createPermissionRes()
}

type CreatePropertyRes interface {
	createPropertyRes()
}

type CreateRoleRes interface {
	createRoleRes()
}

type CreateSubscriberRes interface {
	createSubscriberRes()
}

type CreateUserIdentityRes interface {
	createUserIdentityRes()
}

type CreateUserRes interface {
	createUserRes()
}

type CreateWebHookRes interface {
	createWebHookRes()
}

type DeleteAPIAppliationScopeRes interface {
	deleteAPIAppliationScopeRes()
}

type DeleteAPIRes interface {
	deleteAPIRes()
}

type DeleteAPIScopeRes interface {
	deleteAPIScopeRes()
}

type DeleteApplicationRes interface {
	deleteApplicationRes()
}

type DeleteCallbackURLsRes interface {
	deleteCallbackURLsRes()
}

type DeleteConnectionRes interface {
	deleteConnectionRes()
}

type DeleteEnvironementFeatureFlagOverrideRes interface {
	deleteEnvironementFeatureFlagOverrideRes()
}

type DeleteEnvironementFeatureFlagOverridesRes interface {
	deleteEnvironementFeatureFlagOverridesRes()
}

type DeleteEnvironmentVariableRes interface {
	deleteEnvironmentVariableRes()
}

type DeleteFeatureFlagRes interface {
	deleteFeatureFlagRes()
}

type DeleteIdentityRes interface {
	deleteIdentityRes()
}

type DeleteLogoRes interface {
	deleteLogoRes()
}

type DeleteLogoutURLsRes interface {
	deleteLogoutURLsRes()
}

type DeleteOrganizationFeatureFlagOverrideRes interface {
	deleteOrganizationFeatureFlagOverrideRes()
}

type DeleteOrganizationFeatureFlagOverridesRes interface {
	deleteOrganizationFeatureFlagOverridesRes()
}

type DeleteOrganizationHandleRes interface {
	deleteOrganizationHandleRes()
}

type DeleteOrganizationLogoRes interface {
	deleteOrganizationLogoRes()
}

type DeleteOrganizationRes interface {
	deleteOrganizationRes()
}

type DeleteOrganizationUserAPIScopeRes interface {
	deleteOrganizationUserAPIScopeRes()
}

type DeleteOrganizationUserPermissionRes interface {
	deleteOrganizationUserPermissionRes()
}

type DeleteOrganizationUserRoleRes interface {
	deleteOrganizationUserRoleRes()
}

type DeletePermissionRes interface {
	deletePermissionRes()
}

type DeletePropertyRes interface {
	deletePropertyRes()
}

type DeleteRoleRes interface {
	deleteRoleRes()
}

type DeleteRoleScopeRes interface {
	deleteRoleScopeRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type DeleteUserSessionsRes interface {
	deleteUserSessionsRes()
}

type DeleteWebHookRes interface {
	deleteWebHookRes()
}

type EnableConnectionRes interface {
	enableConnectionRes()
}

type EnableOrgConnectionRes interface {
	enableOrgConnectionRes()
}

type GetAPIRes interface {
	getAPIRes()
}

type GetAPIScopeRes interface {
	getAPIScopeRes()
}

type GetAPIScopesRes interface {
	getAPIScopesRes()
}

type GetAPIsRes interface {
	getAPIsRes()
}

type GetApplicationConnectionsRes interface {
	getApplicationConnectionsRes()
}

type GetApplicationPropertyValuesRes interface {
	getApplicationPropertyValuesRes()
}

type GetApplicationRes interface {
	getApplicationRes()
}

type GetApplicationsRes interface {
	getApplicationsRes()
}

type GetBillingAgreementsRes interface {
	getBillingAgreementsRes()
}

type GetBillingEntitlementsRes interface {
	getBillingEntitlementsRes()
}

type GetBusinessRes interface {
	getBusinessRes()
}

type GetCallbackURLsRes interface {
	getCallbackURLsRes()
}

type GetCategoriesRes interface {
	getCategoriesRes()
}

type GetConnectedAppAuthUrlRes interface {
	getConnectedAppAuthUrlRes()
}

type GetConnectedAppTokenRes interface {
	getConnectedAppTokenRes()
}

type GetConnectionRes interface {
	getConnectionRes()
}

type GetConnectionsRes interface {
	getConnectionsRes()
}

type GetEntitlementRes interface {
	getEntitlementRes()
}

type GetEntitlementsRes interface {
	getEntitlementsRes()
}

type GetEnvironementFeatureFlagsRes interface {
	getEnvironementFeatureFlagsRes()
}

type GetEnvironmentRes interface {
	getEnvironmentRes()
}

type GetEnvironmentVariableRes interface {
	getEnvironmentVariableRes()
}

type GetEnvironmentVariablesRes interface {
	getEnvironmentVariablesRes()
}

type GetEventRes interface {
	getEventRes()
}

type GetEventTypesRes interface {
	getEventTypesRes()
}

type GetFeatureFlagsRes interface {
	getFeatureFlagsRes()
}

type GetIdentityRes interface {
	getIdentityRes()
}

type GetIndustriesRes interface {
	getIndustriesRes()
}

type GetLogoutURLsRes interface {
	getLogoutURLsRes()
}

type GetOrgUserMFARes interface {
	getOrgUserMFARes()
}

type GetOrganizationConnectionsRes interface {
	getOrganizationConnectionsRes()
}

type GetOrganizationFeatureFlagsRes interface {
	getOrganizationFeatureFlagsRes()
}

type GetOrganizationPropertyValuesRes interface {
	getOrganizationPropertyValuesRes()
}

type GetOrganizationRes interface {
	getOrganizationRes()
}

type GetOrganizationUserPermissionsRes interface {
	getOrganizationUserPermissionsRes()
}

type GetOrganizationUserRolesRes interface {
	getOrganizationUserRolesRes()
}

type GetOrganizationUsersRes interface {
	getOrganizationUsersRes()
}

type GetOrganizationsRes interface {
	getOrganizationsRes()
}

type GetPermissionsRes interface {
	getPermissionsRes()
}

type GetPortalLinkRes interface {
	getPortalLinkRes()
}

type GetPropertiesRes interface {
	getPropertiesRes()
}

type GetRolePermissionsRes interface {
	getRolePermissionsRes()
}

type GetRoleRes interface {
	getRoleRes()
}

type GetRoleScopesRes interface {
	getRoleScopesRes()
}

type GetRolesRes interface {
	getRolesRes()
}

type GetSubscriberRes interface {
	getSubscriberRes()
}

type GetSubscribersRes interface {
	getSubscribersRes()
}

type GetTimezonesRes interface {
	getTimezonesRes()
}

type GetUserDataRes interface {
	getUserDataRes()
}

type GetUserIdentitiesRes interface {
	getUserIdentitiesRes()
}

type GetUserPermissionsRes interface {
	getUserPermissionsRes()
}

type GetUserProfileV2Res interface {
	getUserProfileV2Res()
}

type GetUserPropertiesRes interface {
	getUserPropertiesRes()
}

type GetUserPropertyValuesRes interface {
	getUserPropertyValuesRes()
}

type GetUserRolesRes interface {
	getUserRolesRes()
}

type GetUserSessionsRes interface {
	getUserSessionsRes()
}

type GetUsersMFARes interface {
	getUsersMFARes()
}

type GetUsersRes interface {
	getUsersRes()
}

type GetWebHooksRes interface {
	getWebHooksRes()
}

type ReadLogoRes interface {
	readLogoRes()
}

type ReadOrganizationLogoRes interface {
	readOrganizationLogoRes()
}

type RefreshUserClaimsRes interface {
	refreshUserClaimsRes()
}

type RemoveConnectionRes interface {
	removeConnectionRes()
}

type RemoveOrgConnectionRes interface {
	removeOrgConnectionRes()
}

type RemoveOrganizationUserRes interface {
	removeOrganizationUserRes()
}

type RemoveRolePermissionRes interface {
	removeRolePermissionRes()
}

type ReplaceConnectionRes interface {
	replaceConnectionRes()
}

type ReplaceLogoutRedirectURLsRes interface {
	replaceLogoutRedirectURLsRes()
}

type ReplaceMFARes interface {
	replaceMFARes()
}

type ReplaceOrganizationMFARes interface {
	replaceOrganizationMFARes()
}

type ReplaceRedirectCallbackURLsRes interface {
	replaceRedirectCallbackURLsRes()
}

type ResetOrgUserMFAAllRes interface {
	resetOrgUserMFAAllRes()
}

type ResetOrgUserMFARes interface {
	resetOrgUserMFARes()
}

type ResetUsersMFAAllRes interface {
	resetUsersMFAAllRes()
}

type ResetUsersMFARes interface {
	resetUsersMFARes()
}

type RevokeConnectedAppTokenRes interface {
	revokeConnectedAppTokenRes()
}

type SearchUsersRes interface {
	searchUsersRes()
}

type SetUserPasswordRes interface {
	setUserPasswordRes()
}

type TokenIntrospectionRes interface {
	tokenIntrospectionRes()
}

type TokenRevocationRes interface {
	tokenRevocationRes()
}

type UpdateAPIApplicationsRes interface {
	updateAPIApplicationsRes()
}

type UpdateAPIScopeRes interface {
	updateAPIScopeRes()
}

type UpdateApplicationRes interface {
	updateApplicationRes()
}

type UpdateApplicationTokensRes interface {
	updateApplicationTokensRes()
}

type UpdateApplicationsPropertyRes interface {
	updateApplicationsPropertyRes()
}

type UpdateBusinessRes interface {
	updateBusinessRes()
}

type UpdateCategoryRes interface {
	updateCategoryRes()
}

type UpdateConnectionRes interface {
	updateConnectionRes()
}

type UpdateEnvironementFeatureFlagOverrideRes interface {
	updateEnvironementFeatureFlagOverrideRes()
}

type UpdateEnvironmentVariableRes interface {
	updateEnvironmentVariableRes()
}

type UpdateFeatureFlagRes interface {
	updateFeatureFlagRes()
}

type UpdateIdentityRes interface {
	updateIdentityRes()
}

type UpdateOrganizationFeatureFlagOverrideRes interface {
	updateOrganizationFeatureFlagOverrideRes()
}

type UpdateOrganizationPropertiesRes interface {
	updateOrganizationPropertiesRes()
}

type UpdateOrganizationPropertyRes interface {
	updateOrganizationPropertyRes()
}

type UpdateOrganizationRes interface {
	updateOrganizationRes()
}

type UpdateOrganizationSessionsRes interface {
	updateOrganizationSessionsRes()
}

type UpdateOrganizationUsersRes interface {
	updateOrganizationUsersRes()
}

type UpdatePermissionsRes interface {
	updatePermissionsRes()
}

type UpdatePropertyRes interface {
	updatePropertyRes()
}

type UpdateRolePermissionsRes interface {
	updateRolePermissionsRes()
}

type UpdateRolesRes interface {
	updateRolesRes()
}

type UpdateUserFeatureFlagOverrideRes interface {
	updateUserFeatureFlagOverrideRes()
}

type UpdateUserPropertiesRes interface {
	updateUserPropertiesRes()
}

type UpdateUserPropertyRes interface {
	updateUserPropertyRes()
}

type UpdateUserRes interface {
	updateUserRes()
}

type UpdateWebHookRes interface {
	updateWebHookRes()
}
