// Code generated by ogen, DO NOT EDIT.

package management_api

import (
	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/uri"
)

// EncodeURI encodes SearchUsersProperties as URI form.
func (s SearchUsersProperties) EncodeURI(e uri.Encoder) error {
	for k, elem := range s {
		if err := e.EncodeField(k, func(e uri.Encoder) error {

			return e.EncodeArray(func(e uri.Encoder) error {
				for i, item := range elem {
					if err := func() error {
						return e.EncodeValue(conv.StringToString(item))
					}(); err != nil {
						return errors.Wrapf(err, "[%d]", i)
					}
				}
				return nil
			})
		}); err != nil {
			return errors.Wrapf(err, "encode field %q", k)
		}
	}
	return nil
}

// DecodeURI decodes SearchUsersProperties from URI form.
func (s *SearchUsersProperties) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode SearchUsersProperties to nil")
	}
	m := s.init()
	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		var elem []string
		if err := func() error {
			return d.DecodeArray(func(d uri.Decoder) error {
				var elemVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					elemVal = c
					return nil
				}(); err != nil {
					return err
				}
				elem = append(elem, elemVal)
				return nil
			})
		}(); err != nil {
			return errors.Wrapf(err, "decode field %q", k)
		}
		m[string(k)] = elem
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode SearchUsersProperties")
	}

	return nil
}
