// Code generated by ogen, DO NOT EDIT.

package management_api

import (
	"fmt"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/validate"
)

func (s AddLogoType) Validate() error {
	switch s {
	case "dark":
		return nil
	case "light":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s AddOrganizationLogoType) Validate() error {
	switch s {
	case "dark":
		return nil
	case "light":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *CreateApplicationReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CreateApplicationReqType) Validate() error {
	switch s {
	case "reg":
		return nil
	case "spa":
		return nil
	case "m2m":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *CreateCategoryReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Context.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "context",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CreateCategoryReqContext) Validate() error {
	switch s {
	case "org":
		return nil
	case "usr":
		return nil
	case "app":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *CreateConnectionReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Strategy.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "strategy",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CreateConnectionReqStrategy) Validate() error {
	switch s {
	case "oauth2:apple":
		return nil
	case "oauth2:azure_ad":
		return nil
	case "oauth2:bitbucket":
		return nil
	case "oauth2:discord":
		return nil
	case "oauth2:facebook":
		return nil
	case "oauth2:github":
		return nil
	case "oauth2:gitlab":
		return nil
	case "oauth2:google":
		return nil
	case "oauth2:linkedin":
		return nil
	case "oauth2:microsoft":
		return nil
	case "oauth2:patreon":
		return nil
	case "oauth2:slack":
		return nil
	case "oauth2:stripe":
		return nil
	case "oauth2:twitch":
		return nil
	case "oauth2:twitter":
		return nil
	case "oauth2:xero":
		return nil
	case "saml:custom":
		return nil
	case "wsfed:azure_ad":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *CreateFeatureFlagReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.AllowOverrideLevel.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "allow_override_level",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CreateFeatureFlagReqAllowOverrideLevel) Validate() error {
	switch s {
	case "env":
		return nil
	case "org":
		return nil
	case "usr":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s CreateFeatureFlagReqType) Validate() error {
	switch s {
	case "str":
		return nil
	case "int":
		return nil
	case "bool":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *CreateMeterUsageRecordReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.MeterTypeCode.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "meter_type_code",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CreateMeterUsageRecordReqMeterTypeCode) Validate() error {
	switch s {
	case "absolute":
		return nil
	case "delta":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *CreateOrganizationReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.FeatureFlags.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "feature_flags",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CreateOrganizationReqFeatureFlags) Validate() error {
	var failures []validate.FieldError
	for key, elem := range s {
		if err := func() error {
			if err := elem.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			failures = append(failures, validate.FieldError{
				Name:  key,
				Error: err,
			})
		}
	}

	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CreateOrganizationReqFeatureFlagsItem) Validate() error {
	switch s {
	case "str":
		return nil
	case "int":
		return nil
	case "bool":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *CreatePropertyReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Type.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if err := func() error {
		if err := s.Context.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "context",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CreatePropertyReqContext) Validate() error {
	switch s {
	case "org":
		return nil
	case "usr":
		return nil
	case "app":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s CreatePropertyReqType) Validate() error {
	switch s {
	case "single_line_text":
		return nil
	case "multi_line_text":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *CreateUserIdentityReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Type.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CreateUserIdentityReqType) Validate() error {
	switch s {
	case "email":
		return nil
	case "username":
		return nil
	case "phone":
		return nil
	case "enterprise":
		return nil
	case "social":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *CreateUserReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.Identities {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "identities",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *CreateUserReqIdentitiesItem) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Type.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s CreateUserReqIdentitiesItemType) Validate() error {
	switch s {
	case "email":
		return nil
	case "phone":
		return nil
	case "username":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *CreateWebHookReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.EventTypes == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "event_types",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s DeleteLogoType) Validate() error {
	switch s {
	case "dark":
		return nil
	case "light":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s DeleteOrganizationLogoType) Validate() error {
	switch s {
	case "dark":
		return nil
	case "light":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *GetAPIResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.API.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "api",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *GetAPIResponseAPI) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.Applications {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "applications",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *GetAPIResponseAPIApplicationsItem) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Type.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetAPIResponseAPIApplicationsItemType) Validate() error {
	switch s {
	case "Machine to machine (M2M)":
		return nil
	case "Back-end web":
		return nil
	case "Front-end and mobile":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetAPIsExpand) Validate() error {
	switch s {
	case "scopes":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *GetApplicationResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Application.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "application",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *GetApplicationResponseApplication) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Type.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetApplicationResponseApplicationType) Validate() error {
	switch s {
	case "m2m":
		return nil
	case "reg":
		return nil
	case "spa":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetApplicationsSort) Validate() error {
	switch s {
	case "name_asc":
		return nil
	case "name_desc":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetBillingEntitlementsExpand) Validate() error {
	switch s {
	case "plans":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetCategoriesContext) Validate() error {
	switch s {
	case "usr":
		return nil
	case "org":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *GetEnvironmentFeatureFlagsResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.FeatureFlags.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "feature_flags",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetEnvironmentFeatureFlagsResponseFeatureFlags) Validate() error {
	var failures []validate.FieldError
	for key, elem := range s {
		if err := func() error {
			if err := elem.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			failures = append(failures, validate.FieldError{
				Name:  key,
				Error: err,
			})
		}
	}

	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *GetEnvironmentFeatureFlagsResponseFeatureFlagsItem) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Type.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetEnvironmentFeatureFlagsResponseFeatureFlagsItemType) Validate() error {
	switch s {
	case "str":
		return nil
	case "int":
		return nil
	case "bool":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *GetEnvironmentResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Environment.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "environment",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *GetEnvironmentResponseEnvironment) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.ThemeCode.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "theme_code",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ColorScheme.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "color_scheme",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetEnvironmentResponseEnvironmentColorScheme) Validate() error {
	switch s {
	case "light":
		return nil
	case "dark":
		return nil
	case "light dark":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetEnvironmentResponseEnvironmentThemeCode) Validate() error {
	switch s {
	case "light":
		return nil
	case "dark":
		return nil
	case "user_preference":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *GetOrganizationFeatureFlagsResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.FeatureFlags.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "feature_flags",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetOrganizationFeatureFlagsResponseFeatureFlags) Validate() error {
	var failures []validate.FieldError
	for key, elem := range s {
		if err := func() error {
			if err := elem.Validate(); err != nil {
				return err
			}
			return nil
		}(); err != nil {
			failures = append(failures, validate.FieldError{
				Name:  key,
				Error: err,
			})
		}
	}

	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *GetOrganizationFeatureFlagsResponseFeatureFlagsItem) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Type.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetOrganizationFeatureFlagsResponseFeatureFlagsItemType) Validate() error {
	switch s {
	case "str":
		return nil
	case "int":
		return nil
	case "bool":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *GetOrganizationResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.ThemeCode.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "theme_code",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ColorScheme.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "color_scheme",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s GetOrganizationResponseColorScheme) Validate() error {
	switch s {
	case "light":
		return nil
	case "dark":
		return nil
	case "light dark":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetOrganizationResponseThemeCode) Validate() error {
	switch s {
	case "light":
		return nil
	case "dark":
		return nil
	case "user_preference":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetOrganizationUsersSort) Validate() error {
	switch s {
	case "name_asc":
		return nil
	case "name_desc":
		return nil
	case "email_asc":
		return nil
	case "email_desc":
		return nil
	case "id_asc":
		return nil
	case "id_desc":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetOrganizationsSort) Validate() error {
	switch s {
	case "name_asc":
		return nil
	case "name_desc":
		return nil
	case "email_asc":
		return nil
	case "email_desc":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetPermissionsSort) Validate() error {
	switch s {
	case "name_asc":
		return nil
	case "name_desc":
		return nil
	case "id_asc":
		return nil
	case "id_desc":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetPropertiesContext) Validate() error {
	switch s {
	case "usr":
		return nil
	case "org":
		return nil
	case "app":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetRolePermissionsSort) Validate() error {
	switch s {
	case "name_asc":
		return nil
	case "name_desc":
		return nil
	case "id_asc":
		return nil
	case "id_desc":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetRolesSort) Validate() error {
	switch s {
	case "name_asc":
		return nil
	case "name_desc":
		return nil
	case "id_asc":
		return nil
	case "id_desc":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s GetSubscribersSort) Validate() error {
	switch s {
	case "name_asc":
		return nil
	case "name_desc":
		return nil
	case "email_asc":
		return nil
	case "email_desc":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ReplaceMFAReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Policy.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "policy",
			Error: err,
		})
	}
	if err := func() error {
		if s.EnabledFactors == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.EnabledFactors {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "enabled_factors",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ReplaceMFAReqEnabledFactorsItem) Validate() error {
	switch s {
	case "mfa:email":
		return nil
	case "mfa:sms":
		return nil
	case "mfa:authenticator_app":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s ReplaceMFAReqPolicy) Validate() error {
	switch s {
	case "required":
		return nil
	case "off":
		return nil
	case "optional":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ReplaceOrganizationMFAReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.EnabledFactors == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.EnabledFactors {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "enabled_factors",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ReplaceOrganizationMFAReqEnabledFactorsItem) Validate() error {
	switch s {
	case "mfa:email":
		return nil
	case "mfa:sms":
		return nil
	case "mfa:authenticator_app":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s SearchUsersProperties) Validate() error {
	var failures []validate.FieldError
	for key, elem := range s {
		if err := func() error {
			if elem == nil {
				return errors.New("nil is invalid value")
			}
			return nil
		}(); err != nil {
			failures = append(failures, validate.FieldError{
				Name:  key,
				Error: err,
			})
		}
	}

	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *SetUserPasswordReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.HashingMethod.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "hashing_method",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.SaltPosition.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "salt_position",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s SetUserPasswordReqHashingMethod) Validate() error {
	switch s {
	case "bcrypt":
		return nil
	case "crypt":
		return nil
	case "md5":
		return nil
	case "wordpress":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s SetUserPasswordReqSaltPosition) Validate() error {
	switch s {
	case "prefix":
		return nil
	case "suffix":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *TokenIntrospectionReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.TokenTypeHint.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "token_type_hint",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s TokenIntrospectionReqTokenTypeHint) Validate() error {
	switch s {
	case "access_token":
		return nil
	case "refresh_token":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *TokenRevocationReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.TokenTypeHint.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "token_type_hint",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s TokenRevocationReqTokenTypeHint) Validate() error {
	switch s {
	case "access_token":
		return nil
	case "refresh_token":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *UpdateAPIApplicationsReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Applications == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "applications",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s UpdateFeatureFlagAllowOverrideLevel) Validate() error {
	switch s {
	case "env":
		return nil
	case "org":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s UpdateFeatureFlagType) Validate() error {
	switch s {
	case "str":
		return nil
	case "int":
		return nil
	case "bool":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s UpdateOrganizationExpand) Validate() error {
	switch s {
	case "billing":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *UpdateOrganizationReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.ThemeCode.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "theme_code",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s UpdateOrganizationReqThemeCode) Validate() error {
	switch s {
	case "light":
		return nil
	case "dark":
		return nil
	case "user_preference":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *UpdateOrganizationSessionsReq) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.SSOSessionPersistenceMode.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sso_session_persistence_mode",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s UpdateOrganizationSessionsReqSSOSessionPersistenceMode) Validate() error {
	switch s {
	case "persistent":
		return nil
	case "non-persistent":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
