// Code generated by ogen, DO NOT EDIT.

package management_api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AddAPIApplicationScope implements addAPIApplicationScope operation.
//
// Add a scope to an API application.
// <div>
// <code>create:api_application_scopes</code>
// </div>.
//
// POST /api/v1/apis/{api_id}/applications/{application_id}/scopes/{scope_id}
func (UnimplementedHandler) AddAPIApplicationScope(ctx context.Context, params AddAPIApplicationScopeParams) (r AddAPIApplicationScopeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddAPIScope implements addAPIScope operation.
//
// Create a new API scope.
// <div>
// <code>create:api_scopes</code>
// </div>.
//
// POST /api/v1/apis/{api_id}/scopes
func (UnimplementedHandler) AddAPIScope(ctx context.Context, req *AddAPIScopeReq, params AddAPIScopeParams) (r AddAPIScopeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddAPIs implements addAPIs operation.
//
// Register a new API. For more information read [Register and manage APIs](https://docs.kinde.
// com/developer-tools/your-apis/register-manage-apis/).
// <div>
// <code>create:apis</code>
// </div>.
//
// POST /api/v1/apis
func (UnimplementedHandler) AddAPIs(ctx context.Context, req *AddAPIsReq) (r AddAPIsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddLogo implements AddLogo operation.
//
// Add environment logo
// <div>
// <code>update:environments</code>
// </div>.
//
// PUT /api/v1/environment/logos/{type}
func (UnimplementedHandler) AddLogo(ctx context.Context, req *AddLogoReq, params AddLogoParams) (r AddLogoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddLogoutRedirectURLs implements addLogoutRedirectURLs operation.
//
// Add additional logout redirect URLs.
// <div>
// <code>create:application_logout_uris</code>
// </div>.
//
// POST /api/v1/applications/{app_id}/auth_logout_urls
func (UnimplementedHandler) AddLogoutRedirectURLs(ctx context.Context, req *AddLogoutRedirectURLsReq, params AddLogoutRedirectURLsParams) (r AddLogoutRedirectURLsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddOrganizationLogo implements AddOrganizationLogo operation.
//
// Add organization logo
// <div>
// <code>update:organizations</code>
// </div>.
//
// POST /api/v1/organizations/{org_code}/logos/{type}
func (UnimplementedHandler) AddOrganizationLogo(ctx context.Context, req *AddOrganizationLogoReq, params AddOrganizationLogoParams) (r AddOrganizationLogoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddOrganizationUserAPIScope implements addOrganizationUserAPIScope operation.
//
// Add a scope to an organization user api.
// <div>
// <code>create:organization_user_api_scopes</code>
// </div>.
//
// POST /api/v1/organizations/{org_code}/users/{user_id}/apis/{api_id}/scopes/{scope_id}
func (UnimplementedHandler) AddOrganizationUserAPIScope(ctx context.Context, params AddOrganizationUserAPIScopeParams) (r AddOrganizationUserAPIScopeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddOrganizationUsers implements AddOrganizationUsers operation.
//
// Add existing users to an organization.
// <div>
// <code>create:organization_users</code>
// </div>.
//
// POST /api/v1/organizations/{org_code}/users
func (UnimplementedHandler) AddOrganizationUsers(ctx context.Context, req OptAddOrganizationUsersReq, params AddOrganizationUsersParams) (r AddOrganizationUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddRedirectCallbackURLs implements addRedirectCallbackURLs operation.
//
// Add additional redirect callback URLs.
// <div>
// <code>create:applications_redirect_uris</code>
// </div>.
//
// POST /api/v1/applications/{app_id}/auth_redirect_urls
func (UnimplementedHandler) AddRedirectCallbackURLs(ctx context.Context, req *AddRedirectCallbackURLsReq, params AddRedirectCallbackURLsParams) (r AddRedirectCallbackURLsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// AddRoleScope implements AddRoleScope operation.
//
// Add scope to role.
// <div>
// <code>create:role_scopes</code>
// </div>.
//
// POST /api/v1/roles/{role_id}/scopes
func (UnimplementedHandler) AddRoleScope(ctx context.Context, req *AddRoleScopeReq, params AddRoleScopeParams) (r AddRoleScopeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateApplication implements createApplication operation.
//
// Create a new client.
// <div>
// <code>create:applications</code>
// </div>.
//
// POST /api/v1/applications
func (UnimplementedHandler) CreateApplication(ctx context.Context, req *CreateApplicationReq) (r CreateApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateBillingAgreement implements createBillingAgreement operation.
//
// Creates a new billing agreement based on the plan code passed, and cancels the customer's existing
// agreements
// <div>
// <code>create:billing_agreements</code>
// </div>.
//
// POST /api/v1/billing/agreements
func (UnimplementedHandler) CreateBillingAgreement(ctx context.Context, req *CreateBillingAgreementReq) (r CreateBillingAgreementRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCategory implements CreateCategory operation.
//
// Create category.
// <div>
// <code>create:property_categories</code>
// </div>.
//
// POST /api/v1/property_categories
func (UnimplementedHandler) CreateCategory(ctx context.Context, req *CreateCategoryReq) (r CreateCategoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateConnection implements CreateConnection operation.
//
// Create Connection.
// <div>
// <code>create:connections</code>
// </div>.
//
// POST /api/v1/connections
func (UnimplementedHandler) CreateConnection(ctx context.Context, req *CreateConnectionReq) (r CreateConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateEnvironmentVariable implements createEnvironmentVariable operation.
//
// Create a new environment variable. This feature is in beta and admin UI is not yet available.
// <div>
// <code>create:environment_variables</code>
// </div>.
//
// POST /api/v1/environment_variables
func (UnimplementedHandler) CreateEnvironmentVariable(ctx context.Context, req *CreateEnvironmentVariableReq) (r CreateEnvironmentVariableRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateFeatureFlag implements CreateFeatureFlag operation.
//
// Create feature flag.
// <div>
// <code>create:feature_flags</code>
// </div>.
//
// POST /api/v1/feature_flags
func (UnimplementedHandler) CreateFeatureFlag(ctx context.Context, req *CreateFeatureFlagReq) (r CreateFeatureFlagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMeterUsageRecord implements createMeterUsageRecord operation.
//
// Create a new meter usage record
// <div>
// <code>create:meter_usage</code>
// </div>.
//
// POST /api/v1/billing/meter_usage
func (UnimplementedHandler) CreateMeterUsageRecord(ctx context.Context, req *CreateMeterUsageRecordReq) (r CreateMeterUsageRecordRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrganization implements createOrganization operation.
//
// Create a new organization. To learn more read about [multi tenancy using
// organizations](https://docs.kinde.com/build/organizations/multi-tenancy-using-organizations/)
// <div>
// <code>create:organizations</code>
// </div>.
//
// POST /api/v1/organization
func (UnimplementedHandler) CreateOrganization(ctx context.Context, req *CreateOrganizationReq) (r CreateOrganizationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrganizationUserPermission implements CreateOrganizationUserPermission operation.
//
// Add permission to an organization user.
// <div>
// <code>create:organization_user_permissions</code>
// </div>.
//
// POST /api/v1/organizations/{org_code}/users/{user_id}/permissions
func (UnimplementedHandler) CreateOrganizationUserPermission(ctx context.Context, req *CreateOrganizationUserPermissionReq, params CreateOrganizationUserPermissionParams) (r CreateOrganizationUserPermissionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrganizationUserRole implements CreateOrganizationUserRole operation.
//
// Add role to an organization user.
// <div>
// <code>create:organization_user_roles</code>
// </div>.
//
// POST /api/v1/organizations/{org_code}/users/{user_id}/roles
func (UnimplementedHandler) CreateOrganizationUserRole(ctx context.Context, req *CreateOrganizationUserRoleReq, params CreateOrganizationUserRoleParams) (r CreateOrganizationUserRoleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePermission implements CreatePermission operation.
//
// Create a new permission.
// <div>
// <code>create:permissions</code>
// </div>.
//
// POST /api/v1/permissions
func (UnimplementedHandler) CreatePermission(ctx context.Context, req OptCreatePermissionReq) (r CreatePermissionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProperty implements CreateProperty operation.
//
// Create property.
// <div>
// <code>create:properties</code>
// </div>.
//
// POST /api/v1/properties
func (UnimplementedHandler) CreateProperty(ctx context.Context, req *CreatePropertyReq) (r CreatePropertyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateRole implements CreateRole operation.
//
// Create role.
// <div>
// <code>create:roles</code>
// </div>.
//
// POST /api/v1/roles
func (UnimplementedHandler) CreateRole(ctx context.Context, req OptCreateRoleReq) (r CreateRoleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSubscriber implements CreateSubscriber operation.
//
// Create subscriber.
// <div>
// <code>create:subscribers</code>
// </div>.
//
// POST /api/v1/subscribers
func (UnimplementedHandler) CreateSubscriber(ctx context.Context, params CreateSubscriberParams) (r CreateSubscriberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUser implements createUser operation.
//
// Creates a user record and optionally zero or more identities for the user. An example identity
// could be the email
// address of the user.
// <div>
// <code>create:users</code>
// </div>.
//
// POST /api/v1/user
func (UnimplementedHandler) CreateUser(ctx context.Context, req OptCreateUserReq) (r CreateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUserIdentity implements CreateUserIdentity operation.
//
// Creates an identity for a user.
// <div>
// <code>create:user_identities</code>
// </div>.
//
// POST /api/v1/users/{user_id}/identities
func (UnimplementedHandler) CreateUserIdentity(ctx context.Context, req OptCreateUserIdentityReq, params CreateUserIdentityParams) (r CreateUserIdentityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWebHook implements CreateWebHook operation.
//
// Create a webhook
// <div>
// <code>create:webhooks</code>
// </div>.
//
// POST /api/v1/webhooks
func (UnimplementedHandler) CreateWebHook(ctx context.Context, req *CreateWebHookReq) (r CreateWebHookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAPI implements deleteAPI operation.
//
// Delete an API you previously created.
// <div>
// <code>delete:apis</code>
// </div>.
//
// DELETE /api/v1/apis/{api_id}
func (UnimplementedHandler) DeleteAPI(ctx context.Context, params DeleteAPIParams) (r DeleteAPIRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAPIAppliationScope implements deleteAPIAppliationScope operation.
//
// Delete an API application scope you previously created.
// <div>
// <code>delete:apis_application_scopes</code>
// </div>.
//
// DELETE /api/v1/apis/{api_id}/applications/{application_id}/scopes/{scope_id}
func (UnimplementedHandler) DeleteAPIAppliationScope(ctx context.Context, params DeleteAPIAppliationScopeParams) (r DeleteAPIAppliationScopeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAPIScope implements deleteAPIScope operation.
//
// Delete an API scope you previously created.
// <div>
// <code>delete:apis_scopes</code>
// </div>.
//
// DELETE /api/v1/apis/{api_id}/scopes/{scope_id}
func (UnimplementedHandler) DeleteAPIScope(ctx context.Context, params DeleteAPIScopeParams) (r DeleteAPIScopeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteApplication implements deleteApplication operation.
//
// Delete a client / application.
// <div>
// <code>delete:applications</code>
// </div>.
//
// DELETE /api/v1/applications/{application_id}
func (UnimplementedHandler) DeleteApplication(ctx context.Context, params DeleteApplicationParams) (r DeleteApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCallbackURLs implements deleteCallbackURLs operation.
//
// Delete callback URLs.
// <div>
// <code>delete:applications_redirect_uris</code>
// </div>.
//
// DELETE /api/v1/applications/{app_id}/auth_redirect_urls
func (UnimplementedHandler) DeleteCallbackURLs(ctx context.Context, params DeleteCallbackURLsParams) (r DeleteCallbackURLsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteConnection implements deleteConnection operation.
//
// Delete connection.
// <div>
// <code>delete:connections</code>
// </div>.
//
// DELETE /api/v1/connections/{connection_id}
func (UnimplementedHandler) DeleteConnection(ctx context.Context, params DeleteConnectionParams) (r DeleteConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEnvironementFeatureFlagOverride implements DeleteEnvironementFeatureFlagOverride operation.
//
// Delete environment feature flag override.
// <div>
// <code>delete:environment_feature_flags</code>
// </div>.
//
// DELETE /api/v1/environment/feature_flags/{feature_flag_key}
func (UnimplementedHandler) DeleteEnvironementFeatureFlagOverride(ctx context.Context, params DeleteEnvironementFeatureFlagOverrideParams) (r DeleteEnvironementFeatureFlagOverrideRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEnvironementFeatureFlagOverrides implements DeleteEnvironementFeatureFlagOverrides operation.
//
// Delete all environment feature flag overrides.
// <div>
// <code>delete:environment_feature_flags</code>
// </div>.
//
// DELETE /api/v1/environment/feature_flags
func (UnimplementedHandler) DeleteEnvironementFeatureFlagOverrides(ctx context.Context) (r DeleteEnvironementFeatureFlagOverridesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteEnvironmentVariable implements deleteEnvironmentVariable operation.
//
// Delete an environment variable you previously created. This feature is in beta and admin UI is not
// yet available.
// <div>
// <code>delete:environment_variables</code>
// </div>.
//
// DELETE /api/v1/environment_variables/{variable_id}
func (UnimplementedHandler) DeleteEnvironmentVariable(ctx context.Context, params DeleteEnvironmentVariableParams) (r DeleteEnvironmentVariableRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteFeatureFlag implements DeleteFeatureFlag operation.
//
// Delete feature flag
// <div>
// <code>delete:feature_flags</code>
// </div>.
//
// DELETE /api/v1/feature_flags/{feature_flag_key}
func (UnimplementedHandler) DeleteFeatureFlag(ctx context.Context, params DeleteFeatureFlagParams) (r DeleteFeatureFlagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteIdentity implements DeleteIdentity operation.
//
// Delete identity by ID.
// <div>
// <code>delete:identities</code>
// </div>.
//
// DELETE /api/v1/identities/{identity_id}
func (UnimplementedHandler) DeleteIdentity(ctx context.Context, params DeleteIdentityParams) (r DeleteIdentityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteLogo implements DeleteLogo operation.
//
// Delete environment logo
// <div>
// <code>update:environments</code>
// </div>.
//
// DELETE /api/v1/environment/logos/{type}
func (UnimplementedHandler) DeleteLogo(ctx context.Context, params DeleteLogoParams) (r DeleteLogoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteLogoutURLs implements deleteLogoutURLs operation.
//
// Delete logout URLs.
// <div>
// <code>delete:application_logout_uris</code>
// </div>.
//
// DELETE /api/v1/applications/{app_id}/auth_logout_urls
func (UnimplementedHandler) DeleteLogoutURLs(ctx context.Context, params DeleteLogoutURLsParams) (r DeleteLogoutURLsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOrganization implements deleteOrganization operation.
//
// Delete an organization.
// <div>
// <code>delete:organizations</code>
// </div>.
//
// DELETE /api/v1/organization/{org_code}
func (UnimplementedHandler) DeleteOrganization(ctx context.Context, params DeleteOrganizationParams) (r DeleteOrganizationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOrganizationFeatureFlagOverride implements DeleteOrganizationFeatureFlagOverride operation.
//
// Delete organization feature flag override.
// <div>
// <code>delete:organization_feature_flags</code>
// </div>.
//
// DELETE /api/v1/organizations/{org_code}/feature_flags/{feature_flag_key}
func (UnimplementedHandler) DeleteOrganizationFeatureFlagOverride(ctx context.Context, params DeleteOrganizationFeatureFlagOverrideParams) (r DeleteOrganizationFeatureFlagOverrideRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOrganizationFeatureFlagOverrides implements DeleteOrganizationFeatureFlagOverrides operation.
//
// Delete all organization feature flag overrides.
// <div>
// <code>delete:organization_feature_flags</code>
// </div>.
//
// DELETE /api/v1/organizations/{org_code}/feature_flags
func (UnimplementedHandler) DeleteOrganizationFeatureFlagOverrides(ctx context.Context, params DeleteOrganizationFeatureFlagOverridesParams) (r DeleteOrganizationFeatureFlagOverridesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOrganizationHandle implements DeleteOrganizationHandle operation.
//
// Delete organization handle
// <div>
// <code>delete:organization_handles</code>
// </div>.
//
// DELETE /api/v1/organization/{org_code}/handle
func (UnimplementedHandler) DeleteOrganizationHandle(ctx context.Context, params DeleteOrganizationHandleParams) (r DeleteOrganizationHandleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOrganizationLogo implements DeleteOrganizationLogo operation.
//
// Delete organization logo
// <div>
// <code>update:organizations</code>
// </div>.
//
// DELETE /api/v1/organizations/{org_code}/logos/{type}
func (UnimplementedHandler) DeleteOrganizationLogo(ctx context.Context, params DeleteOrganizationLogoParams) (r DeleteOrganizationLogoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOrganizationUserAPIScope implements deleteOrganizationUserAPIScope operation.
//
// Delete a scope from an organization user api you previously created.
// <div>
// <code>delete:organization_user_api_scopes</code>
// </div>.
//
// DELETE /api/v1/organizations/{org_code}/users/{user_id}/apis/{api_id}/scopes/{scope_id}
func (UnimplementedHandler) DeleteOrganizationUserAPIScope(ctx context.Context, params DeleteOrganizationUserAPIScopeParams) (r DeleteOrganizationUserAPIScopeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOrganizationUserPermission implements DeleteOrganizationUserPermission operation.
//
// Delete permission for an organization user.
// <div>
// <code>delete:organization_user_permissions</code>
// </div>.
//
// DELETE /api/v1/organizations/{org_code}/users/{user_id}/permissions/{permission_id}
func (UnimplementedHandler) DeleteOrganizationUserPermission(ctx context.Context, params DeleteOrganizationUserPermissionParams) (r DeleteOrganizationUserPermissionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteOrganizationUserRole implements DeleteOrganizationUserRole operation.
//
// Delete role for an organization user.
// <div>
// <code>delete:organization_user_roles</code>
// </div>.
//
// DELETE /api/v1/organizations/{org_code}/users/{user_id}/roles/{role_id}
func (UnimplementedHandler) DeleteOrganizationUserRole(ctx context.Context, params DeleteOrganizationUserRoleParams) (r DeleteOrganizationUserRoleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePermission implements DeletePermission operation.
//
// Delete permission
// <div>
// <code>delete:permissions</code>
// </div>.
//
// DELETE /api/v1/permissions/{permission_id}
func (UnimplementedHandler) DeletePermission(ctx context.Context, params DeletePermissionParams) (r DeletePermissionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteProperty implements DeleteProperty operation.
//
// Delete property.
// <div>
// <code>delete:properties</code>
// </div>.
//
// DELETE /api/v1/properties/{property_id}
func (UnimplementedHandler) DeleteProperty(ctx context.Context, params DeletePropertyParams) (r DeletePropertyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteRole implements DeleteRole operation.
//
// Delete role
// <div>
// <code>delete:roles</code>
// </div>.
//
// DELETE /api/v1/roles/{role_id}
func (UnimplementedHandler) DeleteRole(ctx context.Context, params DeleteRoleParams) (r DeleteRoleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteRoleScope implements DeleteRoleScope operation.
//
// Delete scope from role.
// <div>
// <code>delete:role_scopes</code>
// </div>.
//
// DELETE /api/v1/roles/{role_id}/scopes/{scope_id}
func (UnimplementedHandler) DeleteRoleScope(ctx context.Context, params DeleteRoleScopeParams) (r DeleteRoleScopeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteUser implements deleteUser operation.
//
// Delete a user record.
// <div>
// <code>delete:users</code>
// </div>.
//
// DELETE /api/v1/user
func (UnimplementedHandler) DeleteUser(ctx context.Context, params DeleteUserParams) (r DeleteUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteUserSessions implements DeleteUserSessions operation.
//
// Invalidate user sessions.
// <div>
// <code>delete:user_sessions</code>
// </div>.
//
// DELETE /api/v1/users/{user_id}/sessions
func (UnimplementedHandler) DeleteUserSessions(ctx context.Context, params DeleteUserSessionsParams) (r DeleteUserSessionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteWebHook implements DeleteWebHook operation.
//
// Delete webhook
// <div>
// <code>delete:webhooks</code>
// </div>.
//
// DELETE /api/v1/webhooks/{webhook_id}
func (UnimplementedHandler) DeleteWebHook(ctx context.Context, params DeleteWebHookParams) (r DeleteWebHookRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EnableConnection implements EnableConnection operation.
//
// Enable an auth connection for an application.
// <div>
// <code>create:application_connections</code>
// </div>.
//
// POST /api/v1/applications/{application_id}/connections/{connection_id}
func (UnimplementedHandler) EnableConnection(ctx context.Context, params EnableConnectionParams) (r EnableConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// EnableOrgConnection implements EnableOrgConnection operation.
//
// Enable an auth connection for an organization.
// <div>
// <code>create:organization_connections</code>
// </div>.
//
// POST /api/v1/organizations/{organization_code}/connections/{connection_id}
func (UnimplementedHandler) EnableOrgConnection(ctx context.Context, params EnableOrgConnectionParams) (r EnableOrgConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAPI implements getAPI operation.
//
// Retrieve API details by ID.
// <div>
// <code>read:apis</code>
// </div>.
//
// GET /api/v1/apis/{api_id}
func (UnimplementedHandler) GetAPI(ctx context.Context, params GetAPIParams) (r GetAPIRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAPIScope implements getAPIScope operation.
//
// Retrieve API scope by API ID.
// <div>
// <code>read:api_scopes</code>
// </div>.
//
// GET /api/v1/apis/{api_id}/scopes/{scope_id}
func (UnimplementedHandler) GetAPIScope(ctx context.Context, params GetAPIScopeParams) (r GetAPIScopeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAPIScopes implements getAPIScopes operation.
//
// Retrieve API scopes by API ID.
// <div>
// <code>read:api_scopes</code>
// </div>.
//
// GET /api/v1/apis/{api_id}/scopes
func (UnimplementedHandler) GetAPIScopes(ctx context.Context, params GetAPIScopesParams) (r GetAPIScopesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAPIs implements getAPIs operation.
//
// Returns a list of your APIs. The APIs are returned sorted by name.
// <div>
// <code>read:apis</code>
// </div>.
//
// GET /api/v1/apis
func (UnimplementedHandler) GetAPIs(ctx context.Context, params GetAPIsParams) (r GetAPIsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplication implements getApplication operation.
//
// Gets an application given the application's ID.
// <div>
// <code>read:applications</code>
// </div>.
//
// GET /api/v1/applications/{application_id}
func (UnimplementedHandler) GetApplication(ctx context.Context, params GetApplicationParams) (r GetApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplicationConnections implements GetApplicationConnections operation.
//
// Gets all connections for an application.
// <div>
// <code>read:application_connections</code>
// </div>.
//
// GET /api/v1/applications/{application_id}/connections
func (UnimplementedHandler) GetApplicationConnections(ctx context.Context, params GetApplicationConnectionsParams) (r GetApplicationConnectionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplicationPropertyValues implements getApplicationPropertyValues operation.
//
// Gets properties for an application by client ID.
// <div>
// <code>read:application_properties</code>
// </div>.
//
// GET /api/v1/applications/{application_id}/properties
func (UnimplementedHandler) GetApplicationPropertyValues(ctx context.Context, params GetApplicationPropertyValuesParams) (r GetApplicationPropertyValuesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetApplications implements getApplications operation.
//
// Get a list of applications / clients.
// <div>
// <code>read:applications</code>
// </div>.
//
// GET /api/v1/applications
func (UnimplementedHandler) GetApplications(ctx context.Context, params GetApplicationsParams) (r GetApplicationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBillingAgreements implements getBillingAgreements operation.
//
// Returns all the agreements a billing customer currently has access to
// <div>
// <code>read:billing_agreements</code>
// </div>.
//
// GET /api/v1/billing/agreements
func (UnimplementedHandler) GetBillingAgreements(ctx context.Context, params GetBillingAgreementsParams) (r GetBillingAgreementsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBillingEntitlements implements getBillingEntitlements operation.
//
// Returns all the entitlements a billing customer currently has access to
// <div>
// <code>read:billing_entitlements</code>
// </div>.
//
// GET /api/v1/billing/entitlements
func (UnimplementedHandler) GetBillingEntitlements(ctx context.Context, params GetBillingEntitlementsParams) (r GetBillingEntitlementsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBusiness implements getBusiness operation.
//
// Get your business details.
// <div>
// <code>read:businesses</code>
// </div>.
//
// GET /api/v1/business
func (UnimplementedHandler) GetBusiness(ctx context.Context) (r GetBusinessRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCallbackURLs implements getCallbackURLs operation.
//
// Returns an application's redirect callback URLs.
// <div>
// <code>read:applications_redirect_uris</code>
// </div>.
//
// GET /api/v1/applications/{app_id}/auth_redirect_urls
func (UnimplementedHandler) GetCallbackURLs(ctx context.Context, params GetCallbackURLsParams) (r GetCallbackURLsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCategories implements GetCategories operation.
//
// Returns a list of categories.
// <div>
// <code>read:property_categories</code>
// </div>.
//
// GET /api/v1/property_categories
func (UnimplementedHandler) GetCategories(ctx context.Context, params GetCategoriesParams) (r GetCategoriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConnectedAppAuthUrl implements GetConnectedAppAuthUrl operation.
//
// Get a URL that authenticates and authorizes a user to a third-party connected app.
// <div>
// <code>read:connected_apps</code>
// </div>.
//
// GET /api/v1/connected_apps/auth_url
func (UnimplementedHandler) GetConnectedAppAuthUrl(ctx context.Context, params GetConnectedAppAuthUrlParams) (r GetConnectedAppAuthUrlRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConnectedAppToken implements GetConnectedAppToken operation.
//
// Get an access token that can be used to call the third-party provider linked to the connected app.
// <div>
// <code>read:connected_apps</code>
// </div>.
//
// GET /api/v1/connected_apps/token
func (UnimplementedHandler) GetConnectedAppToken(ctx context.Context, params GetConnectedAppTokenParams) (r GetConnectedAppTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConnection implements GetConnection operation.
//
// Get Connection.
// <div>
// <code>read:connections</code>
// </div>.
//
// GET /api/v1/connections/{connection_id}
func (UnimplementedHandler) GetConnection(ctx context.Context, params GetConnectionParams) (r GetConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConnections implements GetConnections operation.
//
// Returns a list of authentication connections. Optionally you can filter this by a home realm
// domain.
// <div>
// <code>read:connections</code>
// </div>.
//
// GET /api/v1/connections
func (UnimplementedHandler) GetConnections(ctx context.Context, params GetConnectionsParams) (r GetConnectionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnvironementFeatureFlags implements GetEnvironementFeatureFlags operation.
//
// Get environment feature flags.
// <div>
// <code>read:environment_feature_flags</code>
// </div>.
//
// GET /api/v1/environment/feature_flags
func (UnimplementedHandler) GetEnvironementFeatureFlags(ctx context.Context) (r GetEnvironementFeatureFlagsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnvironment implements getEnvironment operation.
//
// Gets the current environment.
// <div>
// <code>read:environments</code>
// </div>.
//
// GET /api/v1/environment
func (UnimplementedHandler) GetEnvironment(ctx context.Context) (r GetEnvironmentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnvironmentVariable implements getEnvironmentVariable operation.
//
// Retrieve environment variable details by ID. This feature is in beta and admin UI is not yet
// available.
// <div>
// <code>read:environment_variables</code>
// </div>.
//
// GET /api/v1/environment_variables/{variable_id}
func (UnimplementedHandler) GetEnvironmentVariable(ctx context.Context, params GetEnvironmentVariableParams) (r GetEnvironmentVariableRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEnvironmentVariables implements getEnvironmentVariables operation.
//
// Get environment variables. This feature is in beta and admin UI is not yet available.
// <div>
// <code>read:environment_variables</code>
// </div>.
//
// GET /api/v1/environment_variables
func (UnimplementedHandler) GetEnvironmentVariables(ctx context.Context) (r GetEnvironmentVariablesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEvent implements GetEvent operation.
//
// Returns an event
// <div>
// <code>read:events</code>
// </div>.
//
// GET /api/v1/events/{event_id}
func (UnimplementedHandler) GetEvent(ctx context.Context, params GetEventParams) (r GetEventRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEventTypes implements GetEventTypes operation.
//
// Returns a list event type definitions
// <div>
// <code>read:event_types</code>
// </div>.
//
// GET /api/v1/event_types
func (UnimplementedHandler) GetEventTypes(ctx context.Context) (r GetEventTypesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIdentity implements GetIdentity operation.
//
// Returns an identity by ID
// <div>
// <code>read:identities</code>
// </div>.
//
// GET /api/v1/identities/{identity_id}
func (UnimplementedHandler) GetIdentity(ctx context.Context, params GetIdentityParams) (r GetIdentityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIndustries implements getIndustries operation.
//
// Get a list of industries and associated industry keys.
// <div>
// <code>read:industries</code>
// </div>.
//
// GET /api/v1/industries
func (UnimplementedHandler) GetIndustries(ctx context.Context) (r GetIndustriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetLogoutURLs implements getLogoutURLs operation.
//
// Returns an application's logout redirect URLs.
// <div>
// <code>read:application_logout_uris</code>
// </div>.
//
// GET /api/v1/applications/{app_id}/auth_logout_urls
func (UnimplementedHandler) GetLogoutURLs(ctx context.Context, params GetLogoutURLsParams) (r GetLogoutURLsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrgUserMFA implements GetOrgUserMFA operation.
//
// Get an organization user’s MFA configuration.
// <div>
// <code>read:organization_user_mfa</code>
// </div>.
//
// GET /api/v1/organizations/{org_code}/users/{user_id}/mfa
func (UnimplementedHandler) GetOrgUserMFA(ctx context.Context, params GetOrgUserMFAParams) (r GetOrgUserMFARes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrganization implements getOrganization operation.
//
// Retrieve organization details by code.
// <div>
// <code>read:organizations</code>
// </div>.
//
// GET /api/v1/organization
func (UnimplementedHandler) GetOrganization(ctx context.Context, params GetOrganizationParams) (r GetOrganizationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrganizationConnections implements GetOrganizationConnections operation.
//
// Gets all connections for an organization.
// <div>
// <code>read:organization_connections</code>
// </div>.
//
// GET /api/v1/organizations/{organization_code}/connections
func (UnimplementedHandler) GetOrganizationConnections(ctx context.Context, params GetOrganizationConnectionsParams) (r GetOrganizationConnectionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrganizationFeatureFlags implements GetOrganizationFeatureFlags operation.
//
// Get all organization feature flags.
// <div>
// <code>read:organization_feature_flags</code>
// </div>.
//
// GET /api/v1/organizations/{org_code}/feature_flags
func (UnimplementedHandler) GetOrganizationFeatureFlags(ctx context.Context, params GetOrganizationFeatureFlagsParams) (r GetOrganizationFeatureFlagsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrganizationPropertyValues implements GetOrganizationPropertyValues operation.
//
// Gets properties for an organization by org code.
// <div>
// <code>read:organization_properties</code>
// </div>.
//
// GET /api/v1/organizations/{org_code}/properties
func (UnimplementedHandler) GetOrganizationPropertyValues(ctx context.Context, params GetOrganizationPropertyValuesParams) (r GetOrganizationPropertyValuesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrganizationUserPermissions implements GetOrganizationUserPermissions operation.
//
// Get permissions for an organization user.
// <div>
// <code>read:organization_user_permissions</code>
// </div>.
//
// GET /api/v1/organizations/{org_code}/users/{user_id}/permissions
func (UnimplementedHandler) GetOrganizationUserPermissions(ctx context.Context, params GetOrganizationUserPermissionsParams) (r GetOrganizationUserPermissionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrganizationUserRoles implements GetOrganizationUserRoles operation.
//
// Get roles for an organization user.
// <div>
// <code>read:organization_user_roles</code>
// </div>.
//
// GET /api/v1/organizations/{org_code}/users/{user_id}/roles
func (UnimplementedHandler) GetOrganizationUserRoles(ctx context.Context, params GetOrganizationUserRolesParams) (r GetOrganizationUserRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrganizationUsers implements GetOrganizationUsers operation.
//
// Get user details for all members of an organization.
// <div>
// <code>read:organization_users</code>
// </div>.
//
// GET /api/v1/organizations/{org_code}/users
func (UnimplementedHandler) GetOrganizationUsers(ctx context.Context, params GetOrganizationUsersParams) (r GetOrganizationUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrganizations implements getOrganizations operation.
//
// Get a list of organizations.
// <div>
// <code>read:organizations</code>
// </div>.
//
// GET /api/v1/organizations
func (UnimplementedHandler) GetOrganizations(ctx context.Context, params GetOrganizationsParams) (r GetOrganizationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPermissions implements GetPermissions operation.
//
// The returned list can be sorted by permission name or permission ID in ascending or descending
// order. The number of records to return at a time can also be controlled using the `page_size`
// query string parameter.
// <div>
// <code>read:permissions</code>
// </div>.
//
// GET /api/v1/permissions
func (UnimplementedHandler) GetPermissions(ctx context.Context, params GetPermissionsParams) (r GetPermissionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProperties implements GetProperties operation.
//
// Returns a list of properties
// <div>
// <code>read:properties</code>
// </div>.
//
// GET /api/v1/properties
func (UnimplementedHandler) GetProperties(ctx context.Context, params GetPropertiesParams) (r GetPropertiesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRole implements GetRole operation.
//
// Get a role
// <div>
// <code>read:roles</code>
// </div>.
//
// GET /api/v1/roles/{role_id}
func (UnimplementedHandler) GetRole(ctx context.Context, params GetRoleParams) (r GetRoleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRolePermissions implements GetRolePermissions operation.
//
// Get permissions for a role.
// <div>
// <code>read:role_permissions</code>
// </div>.
//
// GET /api/v1/roles/{role_id}/permissions
func (UnimplementedHandler) GetRolePermissions(ctx context.Context, params GetRolePermissionsParams) (r GetRolePermissionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRoleScopes implements GetRoleScopes operation.
//
// Get scopes for a role.
// <div>
// <code>read:role_scopes</code>
// </div>.
//
// GET /api/v1/roles/{role_id}/scopes
func (UnimplementedHandler) GetRoleScopes(ctx context.Context, params GetRoleScopesParams) (r GetRoleScopesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRoles implements GetRoles operation.
//
// The returned list can be sorted by role name or role ID in ascending or descending order. The
// number of records to return at a time can also be controlled using the `page_size` query string
// parameter.
// <div>
// <code>read:roles</code>
// </div>.
//
// GET /api/v1/roles
func (UnimplementedHandler) GetRoles(ctx context.Context, params GetRolesParams) (r GetRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSubscriber implements GetSubscriber operation.
//
// Retrieve a subscriber record.
// <div>
// <code>read:subscribers</code>
// </div>.
//
// GET /api/v1/subscribers/{subscriber_id}
func (UnimplementedHandler) GetSubscriber(ctx context.Context, params GetSubscriberParams) (r GetSubscriberRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSubscribers implements GetSubscribers operation.
//
// The returned list can be sorted by full name or email address
// in ascending or descending order. The number of records to return at a time can also be controlled
// using the `page_size` query
// string parameter.
// <div>
// <code>read:subscribers</code>
// </div>.
//
// GET /api/v1/subscribers
func (UnimplementedHandler) GetSubscribers(ctx context.Context, params GetSubscribersParams) (r GetSubscribersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTimezones implements getTimezones operation.
//
// Get a list of timezones and associated timezone keys.
// <div>
// <code>read:timezones</code>
// </div>.
//
// GET /api/v1/timezones
func (UnimplementedHandler) GetTimezones(ctx context.Context) (r GetTimezonesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserData implements getUserData operation.
//
// Retrieve a user record.
// <div>
// <code>read:users</code>
// </div>.
//
// GET /api/v1/user
func (UnimplementedHandler) GetUserData(ctx context.Context, params GetUserDataParams) (r GetUserDataRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserIdentities implements GetUserIdentities operation.
//
// Gets a list of identities for an user by ID.
// <div>
// <code>read:user_identities</code>
// </div>.
//
// GET /api/v1/users/{user_id}/identities
func (UnimplementedHandler) GetUserIdentities(ctx context.Context, params GetUserIdentitiesParams) (r GetUserIdentitiesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserProfileV2 implements getUserProfileV2 operation.
//
// This endpoint returns a user's ID, names, profile picture URL and email of the currently logged in
// user.
//
// GET /oauth2/v2/user_profile
func (UnimplementedHandler) GetUserProfileV2(ctx context.Context) (r GetUserProfileV2Res, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserPropertyValues implements GetUserPropertyValues operation.
//
// Gets properties for an user by ID.
// <div>
// <code>read:user_properties</code>
// </div>.
//
// GET /api/v1/users/{user_id}/properties
func (UnimplementedHandler) GetUserPropertyValues(ctx context.Context, params GetUserPropertyValuesParams) (r GetUserPropertyValuesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserSessions implements GetUserSessions operation.
//
// Retrieve the list of active sessions for a specific user.
// <div>
// <code>read:user_sessions</code>
// </div>.
//
// GET /api/v1/users/{user_id}/sessions
func (UnimplementedHandler) GetUserSessions(ctx context.Context, params GetUserSessionsParams) (r GetUserSessionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsers implements getUsers operation.
//
// The returned list can be sorted by full name or email address in ascending or descending order.
// The number of records to return at a time can also be controlled using the `page_size` query
// string parameter.
// <div>
// <code>read:users</code>
// </div>.
//
// GET /api/v1/users
func (UnimplementedHandler) GetUsers(ctx context.Context, params GetUsersParams) (r GetUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUsersMFA implements GetUsersMFA operation.
//
// Get a user’s MFA configuration.
// <div>
// <code>read:user_mfa</code>
// </div>.
//
// GET /api/v1/users/{user_id}/mfa
func (UnimplementedHandler) GetUsersMFA(ctx context.Context, params GetUsersMFAParams) (r GetUsersMFARes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWebHooks implements GetWebHooks operation.
//
// List webhooks
// <div>
// <code>read:webhooks</code>
// </div>.
//
// GET /api/v1/webhooks
func (UnimplementedHandler) GetWebHooks(ctx context.Context) (r GetWebHooksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadLogo implements ReadLogo operation.
//
// Read environment logo details
// <div>
// <code>read:environments</code>
// </div>.
//
// GET /api/v1/environment/logos
func (UnimplementedHandler) ReadLogo(ctx context.Context) (r ReadLogoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadOrganizationLogo implements ReadOrganizationLogo operation.
//
// Read organization logo details
// <div>
// <code>read:organizations</code>
// </div>.
//
// GET /api/v1/organizations/{org_code}/logos
func (UnimplementedHandler) ReadOrganizationLogo(ctx context.Context, params ReadOrganizationLogoParams) (r ReadOrganizationLogoRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RefreshUserClaims implements refreshUserClaims operation.
//
// Refreshes the user's claims and invalidates the current cache.
// <div>
// <code>update:user_refresh_claims</code>
// </div>.
//
// POST /api/v1/users/{user_id}/refresh_claims
func (UnimplementedHandler) RefreshUserClaims(ctx context.Context, params RefreshUserClaimsParams) (r RefreshUserClaimsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveConnection implements RemoveConnection operation.
//
// Turn off an auth connection for an application
// <div>
// <code>delete:application_connections</code>
// </div>.
//
// DELETE /api/v1/applications/{application_id}/connections/{connection_id}
func (UnimplementedHandler) RemoveConnection(ctx context.Context, params RemoveConnectionParams) (r RemoveConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveOrgConnection implements RemoveOrgConnection operation.
//
// Turn off an auth connection for an organization
// <div>
// <code>delete:organization_connections</code>
// </div>.
//
// DELETE /api/v1/organizations/{organization_code}/connections/{connection_id}
func (UnimplementedHandler) RemoveOrgConnection(ctx context.Context, params RemoveOrgConnectionParams) (r RemoveOrgConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveOrganizationUser implements RemoveOrganizationUser operation.
//
// Remove user from an organization.
// <div>
// <code>delete:organization_users</code>
// </div>.
//
// DELETE /api/v1/organizations/{org_code}/users/{user_id}
func (UnimplementedHandler) RemoveOrganizationUser(ctx context.Context, params RemoveOrganizationUserParams) (r RemoveOrganizationUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RemoveRolePermission implements RemoveRolePermission operation.
//
// Remove a permission from a role.
// <div>
// <code>delete:role_permissions</code>
// </div>.
//
// DELETE /api/v1/roles/{role_id}/permissions/{permission_id}
func (UnimplementedHandler) RemoveRolePermission(ctx context.Context, params RemoveRolePermissionParams) (r RemoveRolePermissionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReplaceConnection implements ReplaceConnection operation.
//
// Replace Connection Config.
// <div>
// <code>update:connections</code>
// </div>.
//
// PUT /api/v1/connections/{connection_id}
func (UnimplementedHandler) ReplaceConnection(ctx context.Context, req *ReplaceConnectionReq, params ReplaceConnectionParams) (r ReplaceConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReplaceLogoutRedirectURLs implements replaceLogoutRedirectURLs operation.
//
// Replace all logout redirect URLs.
// <div>
// <code>update:application_logout_uris</code>
// </div>.
//
// PUT /api/v1/applications/{app_id}/auth_logout_urls
func (UnimplementedHandler) ReplaceLogoutRedirectURLs(ctx context.Context, req *ReplaceLogoutRedirectURLsReq, params ReplaceLogoutRedirectURLsParams) (r ReplaceLogoutRedirectURLsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReplaceMFA implements ReplaceMFA operation.
//
// Replace MFA Configuration.
// <div>
// <code>update:mfa</code>
// </div>.
//
// PUT /api/v1/mfa
func (UnimplementedHandler) ReplaceMFA(ctx context.Context, req *ReplaceMFAReq) (r ReplaceMFARes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReplaceOrganizationMFA implements ReplaceOrganizationMFA operation.
//
// Replace Organization MFA Configuration.
// <div>
// <code>update:organization_mfa</code>
// </div>.
//
// PUT /api/v1/organizations/{org_code}/mfa
func (UnimplementedHandler) ReplaceOrganizationMFA(ctx context.Context, req *ReplaceOrganizationMFAReq, params ReplaceOrganizationMFAParams) (r ReplaceOrganizationMFARes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReplaceRedirectCallbackURLs implements replaceRedirectCallbackURLs operation.
//
// Replace all redirect callback URLs.
// <div>
// <code>update:applications_redirect_uris</code>
// </div>.
//
// PUT /api/v1/applications/{app_id}/auth_redirect_urls
func (UnimplementedHandler) ReplaceRedirectCallbackURLs(ctx context.Context, req *ReplaceRedirectCallbackURLsReq, params ReplaceRedirectCallbackURLsParams) (r ReplaceRedirectCallbackURLsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResetOrgUserMFA implements ResetOrgUserMFA operation.
//
// Reset a specific organization MFA factor for a user.
// <div>
// <code>delete:organization_user_mfa</code>
// </div>.
//
// DELETE /api/v1/organizations/{org_code}/users/{user_id}/mfa/{factor_id}
func (UnimplementedHandler) ResetOrgUserMFA(ctx context.Context, params ResetOrgUserMFAParams) (r ResetOrgUserMFARes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResetOrgUserMFAAll implements ResetOrgUserMFAAll operation.
//
// Reset all organization MFA factors for a user.
// <div>
// <code>delete:organization_user_mfa</code>
// </div>.
//
// DELETE /api/v1/organizations/{org_code}/users/{user_id}/mfa
func (UnimplementedHandler) ResetOrgUserMFAAll(ctx context.Context, params ResetOrgUserMFAAllParams) (r ResetOrgUserMFAAllRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResetUsersMFA implements ResetUsersMFA operation.
//
// Reset a specific environment MFA factor for a user.
// <div>
// <code>delete:user_mfa</code>
// </div>.
//
// DELETE /api/v1/users/{user_id}/mfa/{factor_id}
func (UnimplementedHandler) ResetUsersMFA(ctx context.Context, params ResetUsersMFAParams) (r ResetUsersMFARes, _ error) {
	return r, ht.ErrNotImplemented
}

// ResetUsersMFAAll implements ResetUsersMFAAll operation.
//
// Reset all environment MFA factors for a user.
// <div>
// <code>delete:user_mfa</code>
// </div>.
//
// DELETE /api/v1/users/{user_id}/mfa
func (UnimplementedHandler) ResetUsersMFAAll(ctx context.Context, params ResetUsersMFAAllParams) (r ResetUsersMFAAllRes, _ error) {
	return r, ht.ErrNotImplemented
}

// RevokeConnectedAppToken implements RevokeConnectedAppToken operation.
//
// Revoke the tokens linked to the connected app session.
// <div>
// <code>create:connected_apps</code>
// </div>.
//
// POST /api/v1/connected_apps/revoke
func (UnimplementedHandler) RevokeConnectedAppToken(ctx context.Context, params RevokeConnectedAppTokenParams) (r RevokeConnectedAppTokenRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SearchUsers implements searchUsers operation.
//
// Search for users based on the provided query string. Set query to '*' to filter by other
// parameters only.
// The number of records to return at a time can be controlled using the `page_size` query string
// parameter.
// <div>
// <code>read:users</code>
// </div>.
//
// GET /api/v1/search/users
func (UnimplementedHandler) SearchUsers(ctx context.Context, params SearchUsersParams) (r SearchUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SetUserPassword implements SetUserPassword operation.
//
// Set user password.
// <div>
// <code>update:user_passwords</code>
// </div>.
//
// PUT /api/v1/users/{user_id}/password
func (UnimplementedHandler) SetUserPassword(ctx context.Context, req *SetUserPasswordReq, params SetUserPasswordParams) (r SetUserPasswordRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TokenIntrospection implements tokenIntrospection operation.
//
// Retrieve information about the provided token.
//
// POST /oauth2/introspect
func (UnimplementedHandler) TokenIntrospection(ctx context.Context, req *TokenIntrospectionReq) (r TokenIntrospectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TokenRevocation implements tokenRevocation operation.
//
// Use this endpoint to invalidate an access or refresh token. The token will no longer be valid for
// use.
//
// POST /oauth2/revoke
func (UnimplementedHandler) TokenRevocation(ctx context.Context, req *TokenRevocationReq) (r TokenRevocationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAPIApplications implements updateAPIApplications operation.
//
// Authorize applications to be allowed to request access tokens for an API
// <div>
// <code>update:apis</code>
// </div>.
//
// PATCH /api/v1/apis/{api_id}/applications
func (UnimplementedHandler) UpdateAPIApplications(ctx context.Context, req *UpdateAPIApplicationsReq, params UpdateAPIApplicationsParams) (r UpdateAPIApplicationsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAPIScope implements updateAPIScope operation.
//
// Update an API scope.
// <div>
// <code>update:api_scopes</code>
// </div>.
//
// PATCH /api/v1/apis/{api_id}/scopes/{scope_id}
func (UnimplementedHandler) UpdateAPIScope(ctx context.Context, req *UpdateAPIScopeReq, params UpdateAPIScopeParams) (r UpdateAPIScopeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateApplication implements updateApplication operation.
//
// Updates a client's settings. For more information, read [Applications in Kinde](https://docs.kinde.
// com/build/applications/about-applications)
// <div>
// <code>update:applications</code>
// </div>.
//
// PATCH /api/v1/applications/{application_id}
func (UnimplementedHandler) UpdateApplication(ctx context.Context, req OptUpdateApplicationReq, params UpdateApplicationParams) (r UpdateApplicationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateApplicationTokens implements updateApplicationTokens operation.
//
// Configure tokens for an application.
// <div>
// <code>update:application_tokens</code>
// </div>.
//
// PATCH /api/v1/applications/{application_id}/tokens
func (UnimplementedHandler) UpdateApplicationTokens(ctx context.Context, req *UpdateApplicationTokensReq, params UpdateApplicationTokensParams) (r UpdateApplicationTokensRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateApplicationsProperty implements updateApplicationsProperty operation.
//
// Update application property value.
// <div>
// <code>update:application_properties</code>
// </div>.
//
// PUT /api/v1/applications/{application_id}/properties/{property_key}
func (UnimplementedHandler) UpdateApplicationsProperty(ctx context.Context, req *UpdateApplicationsPropertyReq, params UpdateApplicationsPropertyParams) (r UpdateApplicationsPropertyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateBusiness implements updateBusiness operation.
//
// Update your business details.
// <div>
// <code>update:businesses</code>
// </div>.
//
// PATCH /api/v1/business
func (UnimplementedHandler) UpdateBusiness(ctx context.Context, req *UpdateBusinessReq) (r UpdateBusinessRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCategory implements UpdateCategory operation.
//
// Update category.
// <div>
// <code>update:property_categories</code>
// </div>.
//
// PUT /api/v1/property_categories/{category_id}
func (UnimplementedHandler) UpdateCategory(ctx context.Context, req *UpdateCategoryReq, params UpdateCategoryParams) (r UpdateCategoryRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateConnection implements UpdateConnection operation.
//
// Update Connection.
// <div>
// <code>update:connections</code>
// </div>.
//
// PATCH /api/v1/connections/{connection_id}
func (UnimplementedHandler) UpdateConnection(ctx context.Context, req *UpdateConnectionReq, params UpdateConnectionParams) (r UpdateConnectionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEnvironementFeatureFlagOverride implements UpdateEnvironementFeatureFlagOverride operation.
//
// Update environment feature flag override.
// <div>
// <code>update:environment_feature_flags</code>
// </div>.
//
// PATCH /api/v1/environment/feature_flags/{feature_flag_key}
func (UnimplementedHandler) UpdateEnvironementFeatureFlagOverride(ctx context.Context, req *UpdateEnvironementFeatureFlagOverrideReq, params UpdateEnvironementFeatureFlagOverrideParams) (r UpdateEnvironementFeatureFlagOverrideRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateEnvironmentVariable implements updateEnvironmentVariable operation.
//
// Update an environment variable you previously created. This feature is in beta and admin UI is not
// yet available.
// <div>
// <code>update:environment_variables</code>
// </div>.
//
// PATCH /api/v1/environment_variables/{variable_id}
func (UnimplementedHandler) UpdateEnvironmentVariable(ctx context.Context, req *UpdateEnvironmentVariableReq, params UpdateEnvironmentVariableParams) (r UpdateEnvironmentVariableRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateFeatureFlag implements UpdateFeatureFlag operation.
//
// Update feature flag.
// <div>
// <code>update:feature_flags</code>
// </div>.
//
// PUT /api/v1/feature_flags/{feature_flag_key}
func (UnimplementedHandler) UpdateFeatureFlag(ctx context.Context, params UpdateFeatureFlagParams) (r UpdateFeatureFlagRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateIdentity implements UpdateIdentity operation.
//
// Update identity by ID.
// <div>
// <code>update:identities</code>
// </div>.
//
// PATCH /api/v1/identities/{identity_id}
func (UnimplementedHandler) UpdateIdentity(ctx context.Context, req *UpdateIdentityReq, params UpdateIdentityParams) (r UpdateIdentityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrganization implements updateOrganization operation.
//
// Update an organization.
// <div>
// <code>update:organizations</code>
// </div>.
//
// PATCH /api/v1/organization/{org_code}
func (UnimplementedHandler) UpdateOrganization(ctx context.Context, req OptUpdateOrganizationReq, params UpdateOrganizationParams) (r UpdateOrganizationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrganizationFeatureFlagOverride implements UpdateOrganizationFeatureFlagOverride operation.
//
// Update organization feature flag override.
// <div>
// <code>update:organization_feature_flags</code>
// </div>.
//
// PATCH /api/v1/organizations/{org_code}/feature_flags/{feature_flag_key}
func (UnimplementedHandler) UpdateOrganizationFeatureFlagOverride(ctx context.Context, params UpdateOrganizationFeatureFlagOverrideParams) (r UpdateOrganizationFeatureFlagOverrideRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrganizationProperties implements UpdateOrganizationProperties operation.
//
// Update organization property values.
// <div>
// <code>update:organization_properties</code>
// </div>.
//
// PATCH /api/v1/organizations/{org_code}/properties
func (UnimplementedHandler) UpdateOrganizationProperties(ctx context.Context, req *UpdateOrganizationPropertiesReq, params UpdateOrganizationPropertiesParams) (r UpdateOrganizationPropertiesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrganizationProperty implements UpdateOrganizationProperty operation.
//
// Update organization property value.
// <div>
// <code>update:organization_properties</code>
// </div>.
//
// PUT /api/v1/organizations/{org_code}/properties/{property_key}
func (UnimplementedHandler) UpdateOrganizationProperty(ctx context.Context, params UpdateOrganizationPropertyParams) (r UpdateOrganizationPropertyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrganizationSessions implements UpdateOrganizationSessions operation.
//
// Update the organization's session configuration.
// <div>
// <code>update:organizations</code>
// </div>.
//
// PATCH /api/v1/organizations/{org_code}/sessions
func (UnimplementedHandler) UpdateOrganizationSessions(ctx context.Context, req *UpdateOrganizationSessionsReq, params UpdateOrganizationSessionsParams) (r UpdateOrganizationSessionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateOrganizationUsers implements UpdateOrganizationUsers operation.
//
// Update users that belong to an organization.
// <div>
// <code>update:organization_users</code>
// </div>.
//
// PATCH /api/v1/organizations/{org_code}/users
func (UnimplementedHandler) UpdateOrganizationUsers(ctx context.Context, req OptUpdateOrganizationUsersReq, params UpdateOrganizationUsersParams) (r UpdateOrganizationUsersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePermissions implements UpdatePermissions operation.
//
// Update permission
// <div>
// <code>update:permissions</code>
// </div>.
//
// PATCH /api/v1/permissions/{permission_id}
func (UnimplementedHandler) UpdatePermissions(ctx context.Context, req OptUpdatePermissionsReq, params UpdatePermissionsParams) (r UpdatePermissionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProperty implements UpdateProperty operation.
//
// Update property.
// <div>
// <code>update:properties</code>
// </div>.
//
// PUT /api/v1/properties/{property_id}
func (UnimplementedHandler) UpdateProperty(ctx context.Context, req *UpdatePropertyReq, params UpdatePropertyParams) (r UpdatePropertyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateRolePermissions implements UpdateRolePermissions operation.
//
// Update role permissions.
// <div>
// <code>update:role_permissions</code>
// </div>.
//
// PATCH /api/v1/roles/{role_id}/permissions
func (UnimplementedHandler) UpdateRolePermissions(ctx context.Context, req *UpdateRolePermissionsReq, params UpdateRolePermissionsParams) (r UpdateRolePermissionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateRoles implements UpdateRoles operation.
//
// Update a role
// <div>
// <code>update:roles</code>
// </div>.
//
// PATCH /api/v1/roles/{role_id}
func (UnimplementedHandler) UpdateRoles(ctx context.Context, req OptUpdateRolesReq, params UpdateRolesParams) (r UpdateRolesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUser implements updateUser operation.
//
// Update a user record.
// <div>
// <code>update:users</code>
// </div>.
//
// PATCH /api/v1/user
func (UnimplementedHandler) UpdateUser(ctx context.Context, req *UpdateUserReq, params UpdateUserParams) (r UpdateUserRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUserFeatureFlagOverride implements UpdateUserFeatureFlagOverride operation.
//
// Update user feature flag override.
// <div>
// <code>update:user_feature_flags</code>
// </div>.
//
// PATCH /api/v1/users/{user_id}/feature_flags/{feature_flag_key}
func (UnimplementedHandler) UpdateUserFeatureFlagOverride(ctx context.Context, params UpdateUserFeatureFlagOverrideParams) (r UpdateUserFeatureFlagOverrideRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUserProperties implements UpdateUserProperties operation.
//
// Update property values.
// <div>
// <code>update:user_properties</code>
// </div>.
//
// PATCH /api/v1/users/{user_id}/properties
func (UnimplementedHandler) UpdateUserProperties(ctx context.Context, req *UpdateUserPropertiesReq, params UpdateUserPropertiesParams) (r UpdateUserPropertiesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUserProperty implements UpdateUserProperty operation.
//
// Update property value.
// <div>
// <code>update:user_properties</code>
// </div>.
//
// PUT /api/v1/users/{user_id}/properties/{property_key}
func (UnimplementedHandler) UpdateUserProperty(ctx context.Context, params UpdateUserPropertyParams) (r UpdateUserPropertyRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWebHook implements UpdateWebHook operation.
//
// Update a webhook
// <div>
// <code>update:webhooks</code>
// </div>.
//
// PATCH /api/v1/webhooks/{webhook_id}
func (UnimplementedHandler) UpdateWebHook(ctx context.Context, req *UpdateWebHookReq, params UpdateWebHookParams) (r UpdateWebHookRes, _ error) {
	return r, ht.ErrNotImplemented
}
