// Code generated by ogen, DO NOT EDIT.

package management_api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleKindeBearerAuth handles kindeBearerAuth security.
	// Accessing the API requires obtaining an access token when login in through Kinde. However,
	// management functions (for e.g. user management) requires an access token obtained using the
	// client_credentials flow.
	HandleKindeBearerAuth(ctx context.Context, operationName OperationName, t KindeBearerAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

func (s *Server) securityKindeBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t KindeBearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	rctx, err := s.sec.HandleKindeBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// KindeBearerAuth provides kindeBearerAuth security value.
	// Accessing the API requires obtaining an access token when login in through Kinde. However,
	// management functions (for e.g. user management) requires an access token obtained using the
	// client_credentials flow.
	KindeBearerAuth(ctx context.Context, operationName OperationName) (KindeBearerAuth, error)
}

func (s *Client) securityKindeBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.KindeBearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"KindeBearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
