// Code generated by ogen, DO NOT EDIT.

package management_api

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleKindeBearerAuth handles kindeBearerAuth security.
	// Requires an access token obtained using the client_credentials flow.
	HandleKindeBearerAuth(ctx context.Context, operationName OperationName, t KindeBearerAuth) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

var operationRolesKindeBearerAuth = map[string][]string{
	AddAPIApplicationScopeOperation:                 []string{},
	AddAPIScopeOperation:                            []string{},
	AddAPIsOperation:                                []string{},
	AddLogoOperation:                                []string{},
	AddLogoutRedirectURLsOperation:                  []string{},
	AddOrganizationLogoOperation:                    []string{},
	AddOrganizationUserAPIScopeOperation:            []string{},
	AddOrganizationUsersOperation:                   []string{},
	AddRedirectCallbackURLsOperation:                []string{},
	AddRoleScopeOperation:                           []string{},
	CreateApiKeyOperation:                           []string{},
	CreateApplicationOperation:                      []string{},
	CreateBillingAgreementOperation:                 []string{},
	CreateCategoryOperation:                         []string{},
	CreateConnectionOperation:                       []string{},
	CreateEnvironmentVariableOperation:              []string{},
	CreateFeatureFlagOperation:                      []string{},
	CreateMeterUsageRecordOperation:                 []string{},
	CreateOrganizationOperation:                     []string{},
	CreateOrganizationUserPermissionOperation:       []string{},
	CreateOrganizationUserRoleOperation:             []string{},
	CreatePermissionOperation:                       []string{},
	CreatePropertyOperation:                         []string{},
	CreateRoleOperation:                             []string{},
	CreateSubscriberOperation:                       []string{},
	CreateUserOperation:                             []string{},
	CreateUserIdentityOperation:                     []string{},
	CreateWebHookOperation:                          []string{},
	DeleteAPIOperation:                              []string{},
	DeleteAPIApplicationScopeOperation:              []string{},
	DeleteAPIScopeOperation:                         []string{},
	DeleteApiKeyOperation:                           []string{},
	DeleteApplicationOperation:                      []string{},
	DeleteCallbackURLsOperation:                     []string{},
	DeleteConnectionOperation:                       []string{},
	DeleteEnvironementFeatureFlagOverrideOperation:  []string{},
	DeleteEnvironementFeatureFlagOverridesOperation: []string{},
	DeleteEnvironmentVariableOperation:              []string{},
	DeleteFeatureFlagOperation:                      []string{},
	DeleteIdentityOperation:                         []string{},
	DeleteLogoOperation:                             []string{},
	DeleteLogoutURLsOperation:                       []string{},
	DeleteOrganizationOperation:                     []string{},
	DeleteOrganizationFeatureFlagOverrideOperation:  []string{},
	DeleteOrganizationFeatureFlagOverridesOperation: []string{},
	DeleteOrganizationHandleOperation:               []string{},
	DeleteOrganizationLogoOperation:                 []string{},
	DeleteOrganizationUserAPIScopeOperation:         []string{},
	DeleteOrganizationUserPermissionOperation:       []string{},
	DeleteOrganizationUserRoleOperation:             []string{},
	DeletePermissionOperation:                       []string{},
	DeletePropertyOperation:                         []string{},
	DeleteRoleOperation:                             []string{},
	DeleteRoleScopeOperation:                        []string{},
	DeleteUserOperation:                             []string{},
	DeleteUserSessionsOperation:                     []string{},
	DeleteWebHookOperation:                          []string{},
	EnableConnectionOperation:                       []string{},
	EnableOrgConnectionOperation:                    []string{},
	GetAPIOperation:                                 []string{},
	GetAPIScopeOperation:                            []string{},
	GetAPIScopesOperation:                           []string{},
	GetAPIsOperation:                                []string{},
	GetApiKeyOperation:                              []string{},
	GetApiKeysOperation:                             []string{},
	GetApplicationOperation:                         []string{},
	GetApplicationConnectionsOperation:              []string{},
	GetApplicationPropertyValuesOperation:           []string{},
	GetApplicationsOperation:                        []string{},
	GetBillingAgreementsOperation:                   []string{},
	GetBillingEntitlementsOperation:                 []string{},
	GetBusinessOperation:                            []string{},
	GetCallbackURLsOperation:                        []string{},
	GetCategoriesOperation:                          []string{},
	GetConnectedAppAuthUrlOperation:                 []string{},
	GetConnectedAppTokenOperation:                   []string{},
	GetConnectionOperation:                          []string{},
	GetConnectionsOperation:                         []string{},
	GetEnvironementFeatureFlagsOperation:            []string{},
	GetEnvironmentOperation:                         []string{},
	GetEnvironmentVariableOperation:                 []string{},
	GetEnvironmentVariablesOperation:                []string{},
	GetEventOperation:                               []string{},
	GetEventTypesOperation:                          []string{},
	GetIdentityOperation:                            []string{},
	GetIndustriesOperation:                          []string{},
	GetLogoutURLsOperation:                          []string{},
	GetOrgUserMFAOperation:                          []string{},
	GetOrganizationOperation:                        []string{},
	GetOrganizationConnectionsOperation:             []string{},
	GetOrganizationFeatureFlagsOperation:            []string{},
	GetOrganizationPropertyValuesOperation:          []string{},
	GetOrganizationUserPermissionsOperation:         []string{},
	GetOrganizationUserRolesOperation:               []string{},
	GetOrganizationUsersOperation:                   []string{},
	GetOrganizationsOperation:                       []string{},
	GetPermissionsOperation:                         []string{},
	GetPropertiesOperation:                          []string{},
	GetRoleOperation:                                []string{},
	GetRolePermissionsOperation:                     []string{},
	GetRoleScopesOperation:                          []string{},
	GetRolesOperation:                               []string{},
	GetSubscriberOperation:                          []string{},
	GetSubscribersOperation:                         []string{},
	GetTimezonesOperation:                           []string{},
	GetUserDataOperation:                            []string{},
	GetUserIdentitiesOperation:                      []string{},
	GetUserPropertyValuesOperation:                  []string{},
	GetUserSessionsOperation:                        []string{},
	GetUsersOperation:                               []string{},
	GetUsersMFAOperation:                            []string{},
	GetWebHooksOperation:                            []string{},
	ReadLogoOperation:                               []string{},
	ReadOrganizationLogoOperation:                   []string{},
	RefreshUserClaimsOperation:                      []string{},
	RemoveConnectionOperation:                       []string{},
	RemoveOrgConnectionOperation:                    []string{},
	RemoveOrganizationUserOperation:                 []string{},
	RemoveRolePermissionOperation:                   []string{},
	ReplaceConnectionOperation:                      []string{},
	ReplaceLogoutRedirectURLsOperation:              []string{},
	ReplaceMFAOperation:                             []string{},
	ReplaceOrganizationMFAOperation:                 []string{},
	ReplaceRedirectCallbackURLsOperation:            []string{},
	ResetOrgUserMFAOperation:                        []string{},
	ResetOrgUserMFAAllOperation:                     []string{},
	ResetUsersMFAOperation:                          []string{},
	ResetUsersMFAAllOperation:                       []string{},
	RevokeConnectedAppTokenOperation:                []string{},
	RotateApiKeyOperation:                           []string{},
	SearchUsersOperation:                            []string{},
	SetUserPasswordOperation:                        []string{},
	UpdateAPIApplicationsOperation:                  []string{},
	UpdateAPIScopeOperation:                         []string{},
	UpdateApplicationOperation:                      []string{},
	UpdateApplicationTokensOperation:                []string{},
	UpdateApplicationsPropertyOperation:             []string{},
	UpdateBusinessOperation:                         []string{},
	UpdateCategoryOperation:                         []string{},
	UpdateConnectionOperation:                       []string{},
	UpdateEnvironementFeatureFlagOverrideOperation:  []string{},
	UpdateEnvironmentVariableOperation:              []string{},
	UpdateFeatureFlagOperation:                      []string{},
	UpdateIdentityOperation:                         []string{},
	UpdateOrganizationOperation:                     []string{},
	UpdateOrganizationFeatureFlagOverrideOperation:  []string{},
	UpdateOrganizationPropertiesOperation:           []string{},
	UpdateOrganizationPropertyOperation:             []string{},
	UpdateOrganizationSessionsOperation:             []string{},
	UpdateOrganizationUsersOperation:                []string{},
	UpdatePermissionsOperation:                      []string{},
	UpdatePropertyOperation:                         []string{},
	UpdateRolePermissionsOperation:                  []string{},
	UpdateRolesOperation:                            []string{},
	UpdateUserOperation:                             []string{},
	UpdateUserFeatureFlagOverrideOperation:          []string{},
	UpdateUserPropertiesOperation:                   []string{},
	UpdateUserPropertyOperation:                     []string{},
	UpdateWebHookOperation:                          []string{},
	VerifyApiKeyOperation:                           []string{},
}

func (s *Server) securityKindeBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t KindeBearerAuth
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesKindeBearerAuth[operationName]
	rctx, err := s.sec.HandleKindeBearerAuth(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// KindeBearerAuth provides kindeBearerAuth security value.
	// Requires an access token obtained using the client_credentials flow.
	KindeBearerAuth(ctx context.Context, operationName OperationName) (KindeBearerAuth, error)
}

func (s *Client) securityKindeBearerAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.KindeBearerAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"KindeBearerAuth\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
