// Code generated by ogen, DO NOT EDIT.

package management_api

// setDefaults set default value of fields.
func (s *ReplaceMFAReq) setDefaults() {
	{
		val := bool(true)
		s.IsRecoveryCodesEnabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ReplaceOrganizationMFAReq) setDefaults() {
	{
		val := bool(true)
		s.IsRecoveryCodesEnabled.SetTo(val)
	}
}
