// Code generated by ogen, DO NOT EDIT.

package management_api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddAPIApplicationScope implements addAPIApplicationScope operation.
	//
	// Add a scope to an API application.
	// <div>
	// <code>create:api_application_scopes</code>
	// </div>.
	//
	// POST /api/v1/apis/{api_id}/applications/{application_id}/scopes/{scope_id}
	AddAPIApplicationScope(ctx context.Context, params AddAPIApplicationScopeParams) (AddAPIApplicationScopeRes, error)
	// AddAPIScope implements addAPIScope operation.
	//
	// Create a new API scope.
	// <div>
	// <code>create:api_scopes</code>
	// </div>.
	//
	// POST /api/v1/apis/{api_id}/scopes
	AddAPIScope(ctx context.Context, req *AddAPIScopeReq, params AddAPIScopeParams) (AddAPIScopeRes, error)
	// AddAPIs implements addAPIs operation.
	//
	// Register a new API. For more information read [Register and manage APIs](https://docs.kinde.
	// com/developer-tools/your-apis/register-manage-apis/).
	// <div>
	// <code>create:apis</code>
	// </div>.
	//
	// POST /api/v1/apis
	AddAPIs(ctx context.Context, req *AddAPIsReq) (AddAPIsRes, error)
	// AddLogo implements AddLogo operation.
	//
	// Add environment logo
	// <div>
	// <code>update:environments</code>
	// </div>.
	//
	// PUT /api/v1/environment/logos/{type}
	AddLogo(ctx context.Context, req *AddLogoReq, params AddLogoParams) (AddLogoRes, error)
	// AddLogoutRedirectURLs implements addLogoutRedirectURLs operation.
	//
	// Add additional logout redirect URLs.
	// <div>
	// <code>create:application_logout_uris</code>
	// </div>.
	//
	// POST /api/v1/applications/{app_id}/auth_logout_urls
	AddLogoutRedirectURLs(ctx context.Context, req *AddLogoutRedirectURLsReq, params AddLogoutRedirectURLsParams) (AddLogoutRedirectURLsRes, error)
	// AddOrganizationLogo implements AddOrganizationLogo operation.
	//
	// Add organization logo
	// <div>
	// <code>update:organizations</code>
	// </div>.
	//
	// POST /api/v1/organizations/{org_code}/logos/{type}
	AddOrganizationLogo(ctx context.Context, req *AddOrganizationLogoReq, params AddOrganizationLogoParams) (AddOrganizationLogoRes, error)
	// AddOrganizationUserAPIScope implements addOrganizationUserAPIScope operation.
	//
	// Add a scope to an organization user api.
	// <div>
	// <code>create:organization_user_api_scopes</code>
	// </div>.
	//
	// POST /api/v1/organizations/{org_code}/users/{user_id}/apis/{api_id}/scopes/{scope_id}
	AddOrganizationUserAPIScope(ctx context.Context, params AddOrganizationUserAPIScopeParams) (AddOrganizationUserAPIScopeRes, error)
	// AddOrganizationUsers implements AddOrganizationUsers operation.
	//
	// Add existing users to an organization.
	// <div>
	// <code>create:organization_users</code>
	// </div>.
	//
	// POST /api/v1/organizations/{org_code}/users
	AddOrganizationUsers(ctx context.Context, req OptAddOrganizationUsersReq, params AddOrganizationUsersParams) (AddOrganizationUsersRes, error)
	// AddRedirectCallbackURLs implements addRedirectCallbackURLs operation.
	//
	// Add additional redirect callback URLs.
	// <div>
	// <code>create:applications_redirect_uris</code>
	// </div>.
	//
	// POST /api/v1/applications/{app_id}/auth_redirect_urls
	AddRedirectCallbackURLs(ctx context.Context, req *AddRedirectCallbackURLsReq, params AddRedirectCallbackURLsParams) (AddRedirectCallbackURLsRes, error)
	// AddRoleScope implements AddRoleScope operation.
	//
	// Add scope to role.
	// <div>
	// <code>create:role_scopes</code>
	// </div>.
	//
	// POST /api/v1/roles/{role_id}/scopes
	AddRoleScope(ctx context.Context, req *AddRoleScopeReq, params AddRoleScopeParams) (AddRoleScopeRes, error)
	// CreateApiKey implements createApiKey operation.
	//
	// Create a new API key.
	// <div>
	// <code>create:api_keys</code>
	// </div>.
	//
	// POST /api/v1/api_keys
	CreateApiKey(ctx context.Context, req *CreateApiKeyReq) (CreateApiKeyRes, error)
	// CreateApplication implements createApplication operation.
	//
	// Create a new client.
	// <div>
	// <code>create:applications</code>
	// </div>.
	//
	// POST /api/v1/applications
	CreateApplication(ctx context.Context, req *CreateApplicationReq) (CreateApplicationRes, error)
	// CreateBillingAgreement implements createBillingAgreement operation.
	//
	// Creates a new billing agreement based on the plan code passed, and cancels the customer's existing
	// agreements
	// <div>
	// <code>create:billing_agreements</code>
	// </div>.
	//
	// POST /api/v1/billing/agreements
	CreateBillingAgreement(ctx context.Context, req *CreateBillingAgreementReq) (CreateBillingAgreementRes, error)
	// CreateCategory implements CreateCategory operation.
	//
	// Create category.
	// <div>
	// <code>create:property_categories</code>
	// </div>.
	//
	// POST /api/v1/property_categories
	CreateCategory(ctx context.Context, req *CreateCategoryReq) (CreateCategoryRes, error)
	// CreateConnection implements CreateConnection operation.
	//
	// Create Connection.
	// <div>
	// <code>create:connections</code>
	// </div>.
	//
	// POST /api/v1/connections
	CreateConnection(ctx context.Context, req *CreateConnectionReq) (CreateConnectionRes, error)
	// CreateEnvironmentVariable implements createEnvironmentVariable operation.
	//
	// Create a new environment variable. This feature is in beta and admin UI is not yet available.
	// <div>
	// <code>create:environment_variables</code>
	// </div>.
	//
	// POST /api/v1/environment_variables
	CreateEnvironmentVariable(ctx context.Context, req *CreateEnvironmentVariableReq) (CreateEnvironmentVariableRes, error)
	// CreateFeatureFlag implements CreateFeatureFlag operation.
	//
	// Create feature flag.
	// <div>
	// <code>create:feature_flags</code>
	// </div>.
	//
	// POST /api/v1/feature_flags
	CreateFeatureFlag(ctx context.Context, req *CreateFeatureFlagReq) (CreateFeatureFlagRes, error)
	// CreateMeterUsageRecord implements createMeterUsageRecord operation.
	//
	// Create a new meter usage record
	// <div>
	// <code>create:meter_usage</code>
	// </div>.
	//
	// POST /api/v1/billing/meter_usage
	CreateMeterUsageRecord(ctx context.Context, req *CreateMeterUsageRecordReq) (CreateMeterUsageRecordRes, error)
	// CreateOrganization implements createOrganization operation.
	//
	// Create a new organization. To learn more read about [multi tenancy using
	// organizations](https://docs.kinde.com/build/organizations/multi-tenancy-using-organizations/)
	// <div>
	// <code>create:organizations</code>
	// </div>.
	//
	// POST /api/v1/organization
	CreateOrganization(ctx context.Context, req *CreateOrganizationReq) (CreateOrganizationRes, error)
	// CreateOrganizationUserPermission implements CreateOrganizationUserPermission operation.
	//
	// Add permission to an organization user.
	// <div>
	// <code>create:organization_user_permissions</code>
	// </div>.
	//
	// POST /api/v1/organizations/{org_code}/users/{user_id}/permissions
	CreateOrganizationUserPermission(ctx context.Context, req *CreateOrganizationUserPermissionReq, params CreateOrganizationUserPermissionParams) (CreateOrganizationUserPermissionRes, error)
	// CreateOrganizationUserRole implements CreateOrganizationUserRole operation.
	//
	// Add role to an organization user.
	// <div>
	// <code>create:organization_user_roles</code>
	// </div>.
	//
	// POST /api/v1/organizations/{org_code}/users/{user_id}/roles
	CreateOrganizationUserRole(ctx context.Context, req *CreateOrganizationUserRoleReq, params CreateOrganizationUserRoleParams) (CreateOrganizationUserRoleRes, error)
	// CreatePermission implements CreatePermission operation.
	//
	// Create a new permission.
	// <div>
	// <code>create:permissions</code>
	// </div>.
	//
	// POST /api/v1/permissions
	CreatePermission(ctx context.Context, req OptCreatePermissionReq) (CreatePermissionRes, error)
	// CreateProperty implements CreateProperty operation.
	//
	// Create property.
	// <div>
	// <code>create:properties</code>
	// </div>.
	//
	// POST /api/v1/properties
	CreateProperty(ctx context.Context, req *CreatePropertyReq) (CreatePropertyRes, error)
	// CreateRole implements CreateRole operation.
	//
	// Create role.
	// <div>
	// <code>create:roles</code>
	// </div>.
	//
	// POST /api/v1/roles
	CreateRole(ctx context.Context, req OptCreateRoleReq) (CreateRoleRes, error)
	// CreateSubscriber implements CreateSubscriber operation.
	//
	// Create subscriber.
	// <div>
	// <code>create:subscribers</code>
	// </div>.
	//
	// POST /api/v1/subscribers
	CreateSubscriber(ctx context.Context, params CreateSubscriberParams) (CreateSubscriberRes, error)
	// CreateUser implements createUser operation.
	//
	// Creates a user record and optionally zero or more identities for the user. An example identity
	// could be the email
	// address of the user.
	// <div>
	// <code>create:users</code>
	// </div>.
	//
	// POST /api/v1/user
	CreateUser(ctx context.Context, req OptCreateUserReq) (CreateUserRes, error)
	// CreateUserIdentity implements CreateUserIdentity operation.
	//
	// Creates an identity for a user.
	// <div>
	// <code>create:user_identities</code>
	// </div>.
	//
	// POST /api/v1/users/{user_id}/identities
	CreateUserIdentity(ctx context.Context, req OptCreateUserIdentityReq, params CreateUserIdentityParams) (CreateUserIdentityRes, error)
	// CreateWebHook implements CreateWebHook operation.
	//
	// Create a webhook
	// <div>
	// <code>create:webhooks</code>
	// </div>.
	//
	// POST /api/v1/webhooks
	CreateWebHook(ctx context.Context, req *CreateWebHookReq) (CreateWebHookRes, error)
	// DeleteAPI implements deleteAPI operation.
	//
	// Delete an API you previously created.
	// <div>
	// <code>delete:apis</code>
	// </div>.
	//
	// DELETE /api/v1/apis/{api_id}
	DeleteAPI(ctx context.Context, params DeleteAPIParams) (DeleteAPIRes, error)
	// DeleteAPIApplicationScope implements deleteAPIApplicationScope operation.
	//
	// Delete an API application scope you previously created.
	// <div>
	// <code>delete:apis_application_scopes</code>
	// </div>.
	//
	// DELETE /api/v1/apis/{api_id}/applications/{application_id}/scopes/{scope_id}
	DeleteAPIApplicationScope(ctx context.Context, params DeleteAPIApplicationScopeParams) (DeleteAPIApplicationScopeRes, error)
	// DeleteAPIScope implements deleteAPIScope operation.
	//
	// Delete an API scope you previously created.
	// <div>
	// <code>delete:apis_scopes</code>
	// </div>.
	//
	// DELETE /api/v1/apis/{api_id}/scopes/{scope_id}
	DeleteAPIScope(ctx context.Context, params DeleteAPIScopeParams) (DeleteAPIScopeRes, error)
	// DeleteApiKey implements deleteApiKey operation.
	//
	// Delete an API key.
	// <div>
	// <code>delete:api_keys</code>
	// </div>.
	//
	// DELETE /api/v1/api_keys/{key_id}
	DeleteApiKey(ctx context.Context, params DeleteApiKeyParams) (DeleteApiKeyRes, error)
	// DeleteApplication implements deleteApplication operation.
	//
	// Delete a client / application.
	// <div>
	// <code>delete:applications</code>
	// </div>.
	//
	// DELETE /api/v1/applications/{application_id}
	DeleteApplication(ctx context.Context, params DeleteApplicationParams) (DeleteApplicationRes, error)
	// DeleteCallbackURLs implements deleteCallbackURLs operation.
	//
	// Delete callback URLs.
	// <div>
	// <code>delete:applications_redirect_uris</code>
	// </div>.
	//
	// DELETE /api/v1/applications/{app_id}/auth_redirect_urls
	DeleteCallbackURLs(ctx context.Context, params DeleteCallbackURLsParams) (DeleteCallbackURLsRes, error)
	// DeleteConnection implements deleteConnection operation.
	//
	// Delete connection.
	// <div>
	// <code>delete:connections</code>
	// </div>.
	//
	// DELETE /api/v1/connections/{connection_id}
	DeleteConnection(ctx context.Context, params DeleteConnectionParams) (DeleteConnectionRes, error)
	// DeleteEnvironementFeatureFlagOverride implements DeleteEnvironementFeatureFlagOverride operation.
	//
	// Delete environment feature flag override.
	// <div>
	// <code>delete:environment_feature_flags</code>
	// </div>.
	//
	// DELETE /api/v1/environment/feature_flags/{feature_flag_key}
	DeleteEnvironementFeatureFlagOverride(ctx context.Context, params DeleteEnvironementFeatureFlagOverrideParams) (DeleteEnvironementFeatureFlagOverrideRes, error)
	// DeleteEnvironementFeatureFlagOverrides implements DeleteEnvironementFeatureFlagOverrides operation.
	//
	// Delete all environment feature flag overrides.
	// <div>
	// <code>delete:environment_feature_flags</code>
	// </div>.
	//
	// DELETE /api/v1/environment/feature_flags
	DeleteEnvironementFeatureFlagOverrides(ctx context.Context) (DeleteEnvironementFeatureFlagOverridesRes, error)
	// DeleteEnvironmentVariable implements deleteEnvironmentVariable operation.
	//
	// Delete an environment variable you previously created. This feature is in beta and admin UI is not
	// yet available.
	// <div>
	// <code>delete:environment_variables</code>
	// </div>.
	//
	// DELETE /api/v1/environment_variables/{variable_id}
	DeleteEnvironmentVariable(ctx context.Context, params DeleteEnvironmentVariableParams) (DeleteEnvironmentVariableRes, error)
	// DeleteFeatureFlag implements DeleteFeatureFlag operation.
	//
	// Delete feature flag
	// <div>
	// <code>delete:feature_flags</code>
	// </div>.
	//
	// DELETE /api/v1/feature_flags/{feature_flag_key}
	DeleteFeatureFlag(ctx context.Context, params DeleteFeatureFlagParams) (DeleteFeatureFlagRes, error)
	// DeleteIdentity implements DeleteIdentity operation.
	//
	// Delete identity by ID.
	// <div>
	// <code>delete:identities</code>
	// </div>.
	//
	// DELETE /api/v1/identities/{identity_id}
	DeleteIdentity(ctx context.Context, params DeleteIdentityParams) (DeleteIdentityRes, error)
	// DeleteLogo implements DeleteLogo operation.
	//
	// Delete environment logo
	// <div>
	// <code>update:environments</code>
	// </div>.
	//
	// DELETE /api/v1/environment/logos/{type}
	DeleteLogo(ctx context.Context, params DeleteLogoParams) (DeleteLogoRes, error)
	// DeleteLogoutURLs implements deleteLogoutURLs operation.
	//
	// Delete logout URLs.
	// <div>
	// <code>delete:application_logout_uris</code>
	// </div>.
	//
	// DELETE /api/v1/applications/{app_id}/auth_logout_urls
	DeleteLogoutURLs(ctx context.Context, params DeleteLogoutURLsParams) (DeleteLogoutURLsRes, error)
	// DeleteOrganization implements deleteOrganization operation.
	//
	// Delete an organization.
	// <div>
	// <code>delete:organizations</code>
	// </div>.
	//
	// DELETE /api/v1/organization/{org_code}
	DeleteOrganization(ctx context.Context, params DeleteOrganizationParams) (DeleteOrganizationRes, error)
	// DeleteOrganizationFeatureFlagOverride implements DeleteOrganizationFeatureFlagOverride operation.
	//
	// Delete organization feature flag override.
	// <div>
	// <code>delete:organization_feature_flags</code>
	// </div>.
	//
	// DELETE /api/v1/organizations/{org_code}/feature_flags/{feature_flag_key}
	DeleteOrganizationFeatureFlagOverride(ctx context.Context, params DeleteOrganizationFeatureFlagOverrideParams) (DeleteOrganizationFeatureFlagOverrideRes, error)
	// DeleteOrganizationFeatureFlagOverrides implements DeleteOrganizationFeatureFlagOverrides operation.
	//
	// Delete all organization feature flag overrides.
	// <div>
	// <code>delete:organization_feature_flags</code>
	// </div>.
	//
	// DELETE /api/v1/organizations/{org_code}/feature_flags
	DeleteOrganizationFeatureFlagOverrides(ctx context.Context, params DeleteOrganizationFeatureFlagOverridesParams) (DeleteOrganizationFeatureFlagOverridesRes, error)
	// DeleteOrganizationHandle implements DeleteOrganizationHandle operation.
	//
	// Delete organization handle
	// <div>
	// <code>delete:organization_handles</code>
	// </div>.
	//
	// DELETE /api/v1/organization/{org_code}/handle
	DeleteOrganizationHandle(ctx context.Context, params DeleteOrganizationHandleParams) (DeleteOrganizationHandleRes, error)
	// DeleteOrganizationLogo implements DeleteOrganizationLogo operation.
	//
	// Delete organization logo
	// <div>
	// <code>update:organizations</code>
	// </div>.
	//
	// DELETE /api/v1/organizations/{org_code}/logos/{type}
	DeleteOrganizationLogo(ctx context.Context, params DeleteOrganizationLogoParams) (DeleteOrganizationLogoRes, error)
	// DeleteOrganizationUserAPIScope implements deleteOrganizationUserAPIScope operation.
	//
	// Delete a scope from an organization user api you previously created.
	// <div>
	// <code>delete:organization_user_api_scopes</code>
	// </div>.
	//
	// DELETE /api/v1/organizations/{org_code}/users/{user_id}/apis/{api_id}/scopes/{scope_id}
	DeleteOrganizationUserAPIScope(ctx context.Context, params DeleteOrganizationUserAPIScopeParams) (DeleteOrganizationUserAPIScopeRes, error)
	// DeleteOrganizationUserPermission implements DeleteOrganizationUserPermission operation.
	//
	// Delete permission for an organization user.
	// <div>
	// <code>delete:organization_user_permissions</code>
	// </div>.
	//
	// DELETE /api/v1/organizations/{org_code}/users/{user_id}/permissions/{permission_id}
	DeleteOrganizationUserPermission(ctx context.Context, params DeleteOrganizationUserPermissionParams) (DeleteOrganizationUserPermissionRes, error)
	// DeleteOrganizationUserRole implements DeleteOrganizationUserRole operation.
	//
	// Delete role for an organization user.
	// <div>
	// <code>delete:organization_user_roles</code>
	// </div>.
	//
	// DELETE /api/v1/organizations/{org_code}/users/{user_id}/roles/{role_id}
	DeleteOrganizationUserRole(ctx context.Context, params DeleteOrganizationUserRoleParams) (DeleteOrganizationUserRoleRes, error)
	// DeletePermission implements DeletePermission operation.
	//
	// Delete permission
	// <div>
	// <code>delete:permissions</code>
	// </div>.
	//
	// DELETE /api/v1/permissions/{permission_id}
	DeletePermission(ctx context.Context, params DeletePermissionParams) (DeletePermissionRes, error)
	// DeleteProperty implements DeleteProperty operation.
	//
	// Delete property.
	// <div>
	// <code>delete:properties</code>
	// </div>.
	//
	// DELETE /api/v1/properties/{property_id}
	DeleteProperty(ctx context.Context, params DeletePropertyParams) (DeletePropertyRes, error)
	// DeleteRole implements DeleteRole operation.
	//
	// Delete role
	// <div>
	// <code>delete:roles</code>
	// </div>.
	//
	// DELETE /api/v1/roles/{role_id}
	DeleteRole(ctx context.Context, params DeleteRoleParams) (DeleteRoleRes, error)
	// DeleteRoleScope implements DeleteRoleScope operation.
	//
	// Delete scope from role.
	// <div>
	// <code>delete:role_scopes</code>
	// </div>.
	//
	// DELETE /api/v1/roles/{role_id}/scopes/{scope_id}
	DeleteRoleScope(ctx context.Context, params DeleteRoleScopeParams) (DeleteRoleScopeRes, error)
	// DeleteUser implements deleteUser operation.
	//
	// Delete a user record.
	// <div>
	// <code>delete:users</code>
	// </div>.
	//
	// DELETE /api/v1/user
	DeleteUser(ctx context.Context, params DeleteUserParams) (DeleteUserRes, error)
	// DeleteUserSessions implements DeleteUserSessions operation.
	//
	// Invalidate user sessions.
	// <div>
	// <code>delete:user_sessions</code>
	// </div>.
	//
	// DELETE /api/v1/users/{user_id}/sessions
	DeleteUserSessions(ctx context.Context, params DeleteUserSessionsParams) (DeleteUserSessionsRes, error)
	// DeleteWebHook implements DeleteWebHook operation.
	//
	// Delete webhook
	// <div>
	// <code>delete:webhooks</code>
	// </div>.
	//
	// DELETE /api/v1/webhooks/{webhook_id}
	DeleteWebHook(ctx context.Context, params DeleteWebHookParams) (DeleteWebHookRes, error)
	// EnableConnection implements EnableConnection operation.
	//
	// Enable an auth connection for an application.
	// <div>
	// <code>create:application_connections</code>
	// </div>.
	//
	// POST /api/v1/applications/{application_id}/connections/{connection_id}
	EnableConnection(ctx context.Context, params EnableConnectionParams) (EnableConnectionRes, error)
	// EnableOrgConnection implements EnableOrgConnection operation.
	//
	// Enable an auth connection for an organization.
	// <div>
	// <code>create:organization_connections</code>
	// </div>.
	//
	// POST /api/v1/organizations/{organization_code}/connections/{connection_id}
	EnableOrgConnection(ctx context.Context, params EnableOrgConnectionParams) (EnableOrgConnectionRes, error)
	// GetAPI implements getAPI operation.
	//
	// Retrieve API details by ID.
	// <div>
	// <code>read:apis</code>
	// </div>.
	//
	// GET /api/v1/apis/{api_id}
	GetAPI(ctx context.Context, params GetAPIParams) (GetAPIRes, error)
	// GetAPIScope implements getAPIScope operation.
	//
	// Retrieve API scope by API ID.
	// <div>
	// <code>read:api_scopes</code>
	// </div>.
	//
	// GET /api/v1/apis/{api_id}/scopes/{scope_id}
	GetAPIScope(ctx context.Context, params GetAPIScopeParams) (GetAPIScopeRes, error)
	// GetAPIScopes implements getAPIScopes operation.
	//
	// Retrieve API scopes by API ID.
	// <div>
	// <code>read:api_scopes</code>
	// </div>.
	//
	// GET /api/v1/apis/{api_id}/scopes
	GetAPIScopes(ctx context.Context, params GetAPIScopesParams) (GetAPIScopesRes, error)
	// GetAPIs implements getAPIs operation.
	//
	// Returns a list of your APIs. The APIs are returned sorted by name.
	// <div>
	// <code>read:apis</code>
	// </div>.
	//
	// GET /api/v1/apis
	GetAPIs(ctx context.Context, params GetAPIsParams) (GetAPIsRes, error)
	// GetApiKey implements getApiKey operation.
	//
	// Retrieve API key details by ID.
	// <div>
	// <code>read:api_keys</code>
	// </div>.
	//
	// GET /api/v1/api_keys/{key_id}
	GetApiKey(ctx context.Context, params GetApiKeyParams) (GetApiKeyRes, error)
	// GetApiKeys implements getApiKeys operation.
	//
	// Returns a list of API keys.
	// <div>
	// <code>read:api_keys</code>
	// </div>.
	//
	// GET /api/v1/api_keys
	GetApiKeys(ctx context.Context, params GetApiKeysParams) (GetApiKeysRes, error)
	// GetApplication implements getApplication operation.
	//
	// Gets an application given the application's ID.
	// <div>
	// <code>read:applications</code>
	// </div>.
	//
	// GET /api/v1/applications/{application_id}
	GetApplication(ctx context.Context, params GetApplicationParams) (GetApplicationRes, error)
	// GetApplicationConnections implements GetApplicationConnections operation.
	//
	// Gets all connections for an application.
	// <div>
	// <code>read:application_connections</code>
	// </div>.
	//
	// GET /api/v1/applications/{application_id}/connections
	GetApplicationConnections(ctx context.Context, params GetApplicationConnectionsParams) (GetApplicationConnectionsRes, error)
	// GetApplicationPropertyValues implements getApplicationPropertyValues operation.
	//
	// Gets properties for an application by client ID.
	// <div>
	// <code>read:application_properties</code>
	// </div>.
	//
	// GET /api/v1/applications/{application_id}/properties
	GetApplicationPropertyValues(ctx context.Context, params GetApplicationPropertyValuesParams) (GetApplicationPropertyValuesRes, error)
	// GetApplications implements getApplications operation.
	//
	// Get a list of applications / clients.
	// <div>
	// <code>read:applications</code>
	// </div>.
	//
	// GET /api/v1/applications
	GetApplications(ctx context.Context, params GetApplicationsParams) (GetApplicationsRes, error)
	// GetBillingAgreements implements getBillingAgreements operation.
	//
	// Returns all the agreements a billing customer currently has access to
	// <div>
	// <code>read:billing_agreements</code>
	// </div>.
	//
	// GET /api/v1/billing/agreements
	GetBillingAgreements(ctx context.Context, params GetBillingAgreementsParams) (GetBillingAgreementsRes, error)
	// GetBillingEntitlements implements getBillingEntitlements operation.
	//
	// Returns all the entitlements a billing customer currently has access to
	// <div>
	// <code>read:billing_entitlements</code>
	// </div>.
	//
	// GET /api/v1/billing/entitlements
	GetBillingEntitlements(ctx context.Context, params GetBillingEntitlementsParams) (GetBillingEntitlementsRes, error)
	// GetBusiness implements getBusiness operation.
	//
	// Get your business details.
	// <div>
	// <code>read:businesses</code>
	// </div>.
	//
	// GET /api/v1/business
	GetBusiness(ctx context.Context) (GetBusinessRes, error)
	// GetCallbackURLs implements getCallbackURLs operation.
	//
	// Returns an application's redirect callback URLs.
	// <div>
	// <code>read:applications_redirect_uris</code>
	// </div>.
	//
	// GET /api/v1/applications/{app_id}/auth_redirect_urls
	GetCallbackURLs(ctx context.Context, params GetCallbackURLsParams) (GetCallbackURLsRes, error)
	// GetCategories implements GetCategories operation.
	//
	// Returns a list of categories.
	// <div>
	// <code>read:property_categories</code>
	// </div>.
	//
	// GET /api/v1/property_categories
	GetCategories(ctx context.Context, params GetCategoriesParams) (GetCategoriesRes, error)
	// GetConnectedAppAuthUrl implements GetConnectedAppAuthUrl operation.
	//
	// Get a URL that authenticates and authorizes a user to a third-party connected app.
	// <div>
	// <code>read:connected_apps</code>
	// </div>.
	//
	// GET /api/v1/connected_apps/auth_url
	GetConnectedAppAuthUrl(ctx context.Context, params GetConnectedAppAuthUrlParams) (GetConnectedAppAuthUrlRes, error)
	// GetConnectedAppToken implements GetConnectedAppToken operation.
	//
	// Get an access token that can be used to call the third-party provider linked to the connected app.
	// <div>
	// <code>read:connected_apps</code>
	// </div>.
	//
	// GET /api/v1/connected_apps/token
	GetConnectedAppToken(ctx context.Context, params GetConnectedAppTokenParams) (GetConnectedAppTokenRes, error)
	// GetConnection implements GetConnection operation.
	//
	// Get Connection.
	// <div>
	// <code>read:connections</code>
	// </div>.
	//
	// GET /api/v1/connections/{connection_id}
	GetConnection(ctx context.Context, params GetConnectionParams) (GetConnectionRes, error)
	// GetConnections implements GetConnections operation.
	//
	// Returns a list of authentication connections. Optionally you can filter this by a home realm
	// domain.
	// <div>
	// <code>read:connections</code>
	// </div>.
	//
	// GET /api/v1/connections
	GetConnections(ctx context.Context, params GetConnectionsParams) (GetConnectionsRes, error)
	// GetEnvironementFeatureFlags implements GetEnvironementFeatureFlags operation.
	//
	// Get environment feature flags.
	// <div>
	// <code>read:environment_feature_flags</code>
	// </div>.
	//
	// GET /api/v1/environment/feature_flags
	GetEnvironementFeatureFlags(ctx context.Context) (GetEnvironementFeatureFlagsRes, error)
	// GetEnvironment implements getEnvironment operation.
	//
	// Gets the current environment.
	// <div>
	// <code>read:environments</code>
	// </div>.
	//
	// GET /api/v1/environment
	GetEnvironment(ctx context.Context) (GetEnvironmentRes, error)
	// GetEnvironmentVariable implements getEnvironmentVariable operation.
	//
	// Retrieve environment variable details by ID. This feature is in beta and admin UI is not yet
	// available.
	// <div>
	// <code>read:environment_variables</code>
	// </div>.
	//
	// GET /api/v1/environment_variables/{variable_id}
	GetEnvironmentVariable(ctx context.Context, params GetEnvironmentVariableParams) (GetEnvironmentVariableRes, error)
	// GetEnvironmentVariables implements getEnvironmentVariables operation.
	//
	// Get environment variables. This feature is in beta and admin UI is not yet available.
	// <div>
	// <code>read:environment_variables</code>
	// </div>.
	//
	// GET /api/v1/environment_variables
	GetEnvironmentVariables(ctx context.Context) (GetEnvironmentVariablesRes, error)
	// GetEvent implements GetEvent operation.
	//
	// Returns an event
	// <div>
	// <code>read:events</code>
	// </div>.
	//
	// GET /api/v1/events/{event_id}
	GetEvent(ctx context.Context, params GetEventParams) (GetEventRes, error)
	// GetEventTypes implements GetEventTypes operation.
	//
	// Returns a list event type definitions
	// <div>
	// <code>read:event_types</code>
	// </div>.
	//
	// GET /api/v1/event_types
	GetEventTypes(ctx context.Context) (GetEventTypesRes, error)
	// GetIdentity implements GetIdentity operation.
	//
	// Returns an identity by ID
	// <div>
	// <code>read:identities</code>
	// </div>.
	//
	// GET /api/v1/identities/{identity_id}
	GetIdentity(ctx context.Context, params GetIdentityParams) (GetIdentityRes, error)
	// GetIndustries implements getIndustries operation.
	//
	// Get a list of industries and associated industry keys.
	// <div>
	// <code>read:industries</code>
	// </div>.
	//
	// GET /api/v1/industries
	GetIndustries(ctx context.Context) (GetIndustriesRes, error)
	// GetLogoutURLs implements getLogoutURLs operation.
	//
	// Returns an application's logout redirect URLs.
	// <div>
	// <code>read:application_logout_uris</code>
	// </div>.
	//
	// GET /api/v1/applications/{app_id}/auth_logout_urls
	GetLogoutURLs(ctx context.Context, params GetLogoutURLsParams) (GetLogoutURLsRes, error)
	// GetOrgUserMFA implements GetOrgUserMFA operation.
	//
	// Get an organization user’s MFA configuration.
	// <div>
	// <code>read:organization_user_mfa</code>
	// </div>.
	//
	// GET /api/v1/organizations/{org_code}/users/{user_id}/mfa
	GetOrgUserMFA(ctx context.Context, params GetOrgUserMFAParams) (GetOrgUserMFARes, error)
	// GetOrganization implements getOrganization operation.
	//
	// Retrieve organization details by code.
	// <div>
	// <code>read:organizations</code>
	// </div>.
	//
	// GET /api/v1/organization
	GetOrganization(ctx context.Context, params GetOrganizationParams) (GetOrganizationRes, error)
	// GetOrganizationConnections implements GetOrganizationConnections operation.
	//
	// Gets all connections for an organization.
	// <div>
	// <code>read:organization_connections</code>
	// </div>.
	//
	// GET /api/v1/organizations/{organization_code}/connections
	GetOrganizationConnections(ctx context.Context, params GetOrganizationConnectionsParams) (GetOrganizationConnectionsRes, error)
	// GetOrganizationFeatureFlags implements GetOrganizationFeatureFlags operation.
	//
	// Get all organization feature flags.
	// <div>
	// <code>read:organization_feature_flags</code>
	// </div>.
	//
	// GET /api/v1/organizations/{org_code}/feature_flags
	GetOrganizationFeatureFlags(ctx context.Context, params GetOrganizationFeatureFlagsParams) (GetOrganizationFeatureFlagsRes, error)
	// GetOrganizationPropertyValues implements GetOrganizationPropertyValues operation.
	//
	// Gets properties for an organization by org code.
	// <div>
	// <code>read:organization_properties</code>
	// </div>.
	//
	// GET /api/v1/organizations/{org_code}/properties
	GetOrganizationPropertyValues(ctx context.Context, params GetOrganizationPropertyValuesParams) (GetOrganizationPropertyValuesRes, error)
	// GetOrganizationUserPermissions implements GetOrganizationUserPermissions operation.
	//
	// Get permissions for an organization user.
	// <div>
	// <code>read:organization_user_permissions</code>
	// </div>.
	//
	// GET /api/v1/organizations/{org_code}/users/{user_id}/permissions
	GetOrganizationUserPermissions(ctx context.Context, params GetOrganizationUserPermissionsParams) (GetOrganizationUserPermissionsRes, error)
	// GetOrganizationUserRoles implements GetOrganizationUserRoles operation.
	//
	// Get roles for an organization user.
	// <div>
	// <code>read:organization_user_roles</code>
	// </div>.
	//
	// GET /api/v1/organizations/{org_code}/users/{user_id}/roles
	GetOrganizationUserRoles(ctx context.Context, params GetOrganizationUserRolesParams) (GetOrganizationUserRolesRes, error)
	// GetOrganizationUsers implements GetOrganizationUsers operation.
	//
	// Get user details for all members of an organization.
	// <div>
	// <code>read:organization_users</code>
	// </div>.
	//
	// GET /api/v1/organizations/{org_code}/users
	GetOrganizationUsers(ctx context.Context, params GetOrganizationUsersParams) (GetOrganizationUsersRes, error)
	// GetOrganizations implements getOrganizations operation.
	//
	// Get a list of organizations.
	// <div>
	// <code>read:organizations</code>
	// </div>.
	//
	// GET /api/v1/organizations
	GetOrganizations(ctx context.Context, params GetOrganizationsParams) (GetOrganizationsRes, error)
	// GetPermissions implements GetPermissions operation.
	//
	// The returned list can be sorted by permission name or permission ID in ascending or descending
	// order. The number of records to return at a time can also be controlled using the `page_size`
	// query string parameter.
	// <div>
	// <code>read:permissions</code>
	// </div>.
	//
	// GET /api/v1/permissions
	GetPermissions(ctx context.Context, params GetPermissionsParams) (GetPermissionsRes, error)
	// GetProperties implements GetProperties operation.
	//
	// Returns a list of properties
	// <div>
	// <code>read:properties</code>
	// </div>.
	//
	// GET /api/v1/properties
	GetProperties(ctx context.Context, params GetPropertiesParams) (GetPropertiesRes, error)
	// GetRole implements GetRole operation.
	//
	// Get a role
	// <div>
	// <code>read:roles</code>
	// </div>.
	//
	// GET /api/v1/roles/{role_id}
	GetRole(ctx context.Context, params GetRoleParams) (GetRoleRes, error)
	// GetRolePermissions implements GetRolePermissions operation.
	//
	// Get permissions for a role.
	// <div>
	// <code>read:role_permissions</code>
	// </div>.
	//
	// GET /api/v1/roles/{role_id}/permissions
	GetRolePermissions(ctx context.Context, params GetRolePermissionsParams) (GetRolePermissionsRes, error)
	// GetRoleScopes implements GetRoleScopes operation.
	//
	// Get scopes for a role.
	// <div>
	// <code>read:role_scopes</code>
	// </div>.
	//
	// GET /api/v1/roles/{role_id}/scopes
	GetRoleScopes(ctx context.Context, params GetRoleScopesParams) (GetRoleScopesRes, error)
	// GetRoles implements GetRoles operation.
	//
	// The returned list can be sorted by role name or role ID in ascending or descending order. The
	// number of records to return at a time can also be controlled using the `page_size` query string
	// parameter.
	// <div>
	// <code>read:roles</code>
	// </div>.
	//
	// GET /api/v1/roles
	GetRoles(ctx context.Context, params GetRolesParams) (GetRolesRes, error)
	// GetSubscriber implements GetSubscriber operation.
	//
	// Retrieve a subscriber record.
	// <div>
	// <code>read:subscribers</code>
	// </div>.
	//
	// GET /api/v1/subscribers/{subscriber_id}
	GetSubscriber(ctx context.Context, params GetSubscriberParams) (GetSubscriberRes, error)
	// GetSubscribers implements GetSubscribers operation.
	//
	// The returned list can be sorted by full name or email address
	// in ascending or descending order. The number of records to return at a time can also be controlled
	// using the `page_size` query
	// string parameter.
	// <div>
	// <code>read:subscribers</code>
	// </div>.
	//
	// GET /api/v1/subscribers
	GetSubscribers(ctx context.Context, params GetSubscribersParams) (GetSubscribersRes, error)
	// GetTimezones implements getTimezones operation.
	//
	// Get a list of timezones and associated timezone keys.
	// <div>
	// <code>read:timezones</code>
	// </div>.
	//
	// GET /api/v1/timezones
	GetTimezones(ctx context.Context) (GetTimezonesRes, error)
	// GetUserData implements getUserData operation.
	//
	// Retrieve a user record.
	// <div>
	// <code>read:users</code>
	// </div>.
	//
	// GET /api/v1/user
	GetUserData(ctx context.Context, params GetUserDataParams) (GetUserDataRes, error)
	// GetUserIdentities implements GetUserIdentities operation.
	//
	// Gets a list of identities for an user by ID.
	// <div>
	// <code>read:user_identities</code>
	// </div>.
	//
	// GET /api/v1/users/{user_id}/identities
	GetUserIdentities(ctx context.Context, params GetUserIdentitiesParams) (GetUserIdentitiesRes, error)
	// GetUserPropertyValues implements GetUserPropertyValues operation.
	//
	// Gets properties for an user by ID.
	// <div>
	// <code>read:user_properties</code>
	// </div>.
	//
	// GET /api/v1/users/{user_id}/properties
	GetUserPropertyValues(ctx context.Context, params GetUserPropertyValuesParams) (GetUserPropertyValuesRes, error)
	// GetUserSessions implements GetUserSessions operation.
	//
	// Retrieve the list of active sessions for a specific user.
	// <div>
	// <code>read:user_sessions</code>
	// </div>.
	//
	// GET /api/v1/users/{user_id}/sessions
	GetUserSessions(ctx context.Context, params GetUserSessionsParams) (GetUserSessionsRes, error)
	// GetUsers implements getUsers operation.
	//
	// The returned list can be sorted by full name or email address in ascending or descending order.
	// The number of records to return at a time can also be controlled using the `page_size` query
	// string parameter.
	// <div>
	// <code>read:users</code>
	// </div>.
	//
	// GET /api/v1/users
	GetUsers(ctx context.Context, params GetUsersParams) (GetUsersRes, error)
	// GetUsersMFA implements GetUsersMFA operation.
	//
	// Get a user’s MFA configuration.
	// <div>
	// <code>read:user_mfa</code>
	// </div>.
	//
	// GET /api/v1/users/{user_id}/mfa
	GetUsersMFA(ctx context.Context, params GetUsersMFAParams) (GetUsersMFARes, error)
	// GetWebHooks implements GetWebHooks operation.
	//
	// List webhooks
	// <div>
	// <code>read:webhooks</code>
	// </div>.
	//
	// GET /api/v1/webhooks
	GetWebHooks(ctx context.Context) (GetWebHooksRes, error)
	// ReadLogo implements ReadLogo operation.
	//
	// Read environment logo details
	// <div>
	// <code>read:environments</code>
	// </div>.
	//
	// GET /api/v1/environment/logos
	ReadLogo(ctx context.Context) (ReadLogoRes, error)
	// ReadOrganizationLogo implements ReadOrganizationLogo operation.
	//
	// Read organization logo details
	// <div>
	// <code>read:organizations</code>
	// </div>.
	//
	// GET /api/v1/organizations/{org_code}/logos
	ReadOrganizationLogo(ctx context.Context, params ReadOrganizationLogoParams) (ReadOrganizationLogoRes, error)
	// RefreshUserClaims implements refreshUserClaims operation.
	//
	// Refreshes the user's claims and invalidates the current cache.
	// <div>
	// <code>update:user_refresh_claims</code>
	// </div>.
	//
	// POST /api/v1/users/{user_id}/refresh_claims
	RefreshUserClaims(ctx context.Context, params RefreshUserClaimsParams) (RefreshUserClaimsRes, error)
	// RemoveConnection implements RemoveConnection operation.
	//
	// Turn off an auth connection for an application
	// <div>
	// <code>delete:application_connections</code>
	// </div>.
	//
	// DELETE /api/v1/applications/{application_id}/connections/{connection_id}
	RemoveConnection(ctx context.Context, params RemoveConnectionParams) (RemoveConnectionRes, error)
	// RemoveOrgConnection implements RemoveOrgConnection operation.
	//
	// Turn off an auth connection for an organization
	// <div>
	// <code>delete:organization_connections</code>
	// </div>.
	//
	// DELETE /api/v1/organizations/{organization_code}/connections/{connection_id}
	RemoveOrgConnection(ctx context.Context, params RemoveOrgConnectionParams) (RemoveOrgConnectionRes, error)
	// RemoveOrganizationUser implements RemoveOrganizationUser operation.
	//
	// Remove user from an organization.
	// <div>
	// <code>delete:organization_users</code>
	// </div>.
	//
	// DELETE /api/v1/organizations/{org_code}/users/{user_id}
	RemoveOrganizationUser(ctx context.Context, params RemoveOrganizationUserParams) (RemoveOrganizationUserRes, error)
	// RemoveRolePermission implements RemoveRolePermission operation.
	//
	// Remove a permission from a role.
	// <div>
	// <code>delete:role_permissions</code>
	// </div>.
	//
	// DELETE /api/v1/roles/{role_id}/permissions/{permission_id}
	RemoveRolePermission(ctx context.Context, params RemoveRolePermissionParams) (RemoveRolePermissionRes, error)
	// ReplaceConnection implements ReplaceConnection operation.
	//
	// Replace Connection Config.
	// <div>
	// <code>update:connections</code>
	// </div>.
	//
	// PUT /api/v1/connections/{connection_id}
	ReplaceConnection(ctx context.Context, req *ReplaceConnectionReq, params ReplaceConnectionParams) (ReplaceConnectionRes, error)
	// ReplaceLogoutRedirectURLs implements replaceLogoutRedirectURLs operation.
	//
	// Replace all logout redirect URLs.
	// <div>
	// <code>update:application_logout_uris</code>
	// </div>.
	//
	// PUT /api/v1/applications/{app_id}/auth_logout_urls
	ReplaceLogoutRedirectURLs(ctx context.Context, req *ReplaceLogoutRedirectURLsReq, params ReplaceLogoutRedirectURLsParams) (ReplaceLogoutRedirectURLsRes, error)
	// ReplaceMFA implements ReplaceMFA operation.
	//
	// Replace MFA Configuration.
	// <div>
	// <code>update:mfa</code>
	// </div>.
	//
	// PUT /api/v1/mfa
	ReplaceMFA(ctx context.Context, req *ReplaceMFAReq) (ReplaceMFARes, error)
	// ReplaceOrganizationMFA implements ReplaceOrganizationMFA operation.
	//
	// Replace Organization MFA Configuration.
	// <div>
	// <code>update:organization_mfa</code>
	// </div>.
	//
	// PUT /api/v1/organizations/{org_code}/mfa
	ReplaceOrganizationMFA(ctx context.Context, req *ReplaceOrganizationMFAReq, params ReplaceOrganizationMFAParams) (ReplaceOrganizationMFARes, error)
	// ReplaceRedirectCallbackURLs implements replaceRedirectCallbackURLs operation.
	//
	// Replace all redirect callback URLs.
	// <div>
	// <code>update:applications_redirect_uris</code>
	// </div>.
	//
	// PUT /api/v1/applications/{app_id}/auth_redirect_urls
	ReplaceRedirectCallbackURLs(ctx context.Context, req *ReplaceRedirectCallbackURLsReq, params ReplaceRedirectCallbackURLsParams) (ReplaceRedirectCallbackURLsRes, error)
	// ResetOrgUserMFA implements ResetOrgUserMFA operation.
	//
	// Reset a specific organization MFA factor for a user.
	// <div>
	// <code>delete:organization_user_mfa</code>
	// </div>.
	//
	// DELETE /api/v1/organizations/{org_code}/users/{user_id}/mfa/{factor_id}
	ResetOrgUserMFA(ctx context.Context, params ResetOrgUserMFAParams) (ResetOrgUserMFARes, error)
	// ResetOrgUserMFAAll implements ResetOrgUserMFAAll operation.
	//
	// Reset all organization MFA factors for a user.
	// <div>
	// <code>delete:organization_user_mfa</code>
	// </div>.
	//
	// DELETE /api/v1/organizations/{org_code}/users/{user_id}/mfa
	ResetOrgUserMFAAll(ctx context.Context, params ResetOrgUserMFAAllParams) (ResetOrgUserMFAAllRes, error)
	// ResetUsersMFA implements ResetUsersMFA operation.
	//
	// Reset a specific environment MFA factor for a user.
	// <div>
	// <code>delete:user_mfa</code>
	// </div>.
	//
	// DELETE /api/v1/users/{user_id}/mfa/{factor_id}
	ResetUsersMFA(ctx context.Context, params ResetUsersMFAParams) (ResetUsersMFARes, error)
	// ResetUsersMFAAll implements ResetUsersMFAAll operation.
	//
	// Reset all environment MFA factors for a user.
	// <div>
	// <code>delete:user_mfa</code>
	// </div>.
	//
	// DELETE /api/v1/users/{user_id}/mfa
	ResetUsersMFAAll(ctx context.Context, params ResetUsersMFAAllParams) (ResetUsersMFAAllRes, error)
	// RevokeConnectedAppToken implements RevokeConnectedAppToken operation.
	//
	// Revoke the tokens linked to the connected app session.
	// <div>
	// <code>create:connected_apps</code>
	// </div>.
	//
	// POST /api/v1/connected_apps/revoke
	RevokeConnectedAppToken(ctx context.Context, params RevokeConnectedAppTokenParams) (RevokeConnectedAppTokenRes, error)
	// RotateApiKey implements rotateApiKey operation.
	//
	// Rotate an API key to generate a new key while maintaining the same permissions and associations.
	// <div>
	// <code>update:api_keys</code>
	// </div>.
	//
	// PUT /api/v1/api_keys/{key_id}
	RotateApiKey(ctx context.Context, params RotateApiKeyParams) (RotateApiKeyRes, error)
	// SearchUsers implements searchUsers operation.
	//
	// Search for users based on the provided query string. Set query to '*' to filter by other
	// parameters only.
	// The number of records to return at a time can be controlled using the `page_size` query string
	// parameter.
	// <div>
	// <code>read:users</code>
	// </div>.
	//
	// GET /api/v1/search/users
	SearchUsers(ctx context.Context, params SearchUsersParams) (SearchUsersRes, error)
	// SetUserPassword implements SetUserPassword operation.
	//
	// Set user password.
	// <div>
	// <code>update:user_passwords</code>
	// </div>.
	//
	// PUT /api/v1/users/{user_id}/password
	SetUserPassword(ctx context.Context, req *SetUserPasswordReq, params SetUserPasswordParams) (SetUserPasswordRes, error)
	// UpdateAPIApplications implements updateAPIApplications operation.
	//
	// Authorize applications to be allowed to request access tokens for an API
	// <div>
	// <code>update:apis</code>
	// </div>.
	//
	// PATCH /api/v1/apis/{api_id}/applications
	UpdateAPIApplications(ctx context.Context, req *UpdateAPIApplicationsReq, params UpdateAPIApplicationsParams) (UpdateAPIApplicationsRes, error)
	// UpdateAPIScope implements updateAPIScope operation.
	//
	// Update an API scope.
	// <div>
	// <code>update:api_scopes</code>
	// </div>.
	//
	// PATCH /api/v1/apis/{api_id}/scopes/{scope_id}
	UpdateAPIScope(ctx context.Context, req *UpdateAPIScopeReq, params UpdateAPIScopeParams) (UpdateAPIScopeRes, error)
	// UpdateApplication implements updateApplication operation.
	//
	// Updates a client's settings. For more information, read [Applications in Kinde](https://docs.kinde.
	// com/build/applications/about-applications)
	// <div>
	// <code>update:applications</code>
	// </div>.
	//
	// PATCH /api/v1/applications/{application_id}
	UpdateApplication(ctx context.Context, req OptUpdateApplicationReq, params UpdateApplicationParams) (UpdateApplicationRes, error)
	// UpdateApplicationTokens implements updateApplicationTokens operation.
	//
	// Configure tokens for an application.
	// <div>
	// <code>update:application_tokens</code>
	// </div>.
	//
	// PATCH /api/v1/applications/{application_id}/tokens
	UpdateApplicationTokens(ctx context.Context, req *UpdateApplicationTokensReq, params UpdateApplicationTokensParams) (UpdateApplicationTokensRes, error)
	// UpdateApplicationsProperty implements updateApplicationsProperty operation.
	//
	// Update application property value.
	// <div>
	// <code>update:application_properties</code>
	// </div>.
	//
	// PUT /api/v1/applications/{application_id}/properties/{property_key}
	UpdateApplicationsProperty(ctx context.Context, req *UpdateApplicationsPropertyReq, params UpdateApplicationsPropertyParams) (UpdateApplicationsPropertyRes, error)
	// UpdateBusiness implements updateBusiness operation.
	//
	// Update your business details.
	// <div>
	// <code>update:businesses</code>
	// </div>.
	//
	// PATCH /api/v1/business
	UpdateBusiness(ctx context.Context, req *UpdateBusinessReq) (UpdateBusinessRes, error)
	// UpdateCategory implements UpdateCategory operation.
	//
	// Update category.
	// <div>
	// <code>update:property_categories</code>
	// </div>.
	//
	// PUT /api/v1/property_categories/{category_id}
	UpdateCategory(ctx context.Context, req *UpdateCategoryReq, params UpdateCategoryParams) (UpdateCategoryRes, error)
	// UpdateConnection implements UpdateConnection operation.
	//
	// Update Connection.
	// <div>
	// <code>update:connections</code>
	// </div>.
	//
	// PATCH /api/v1/connections/{connection_id}
	UpdateConnection(ctx context.Context, req *UpdateConnectionReq, params UpdateConnectionParams) (UpdateConnectionRes, error)
	// UpdateEnvironementFeatureFlagOverride implements UpdateEnvironementFeatureFlagOverride operation.
	//
	// Update environment feature flag override.
	// <div>
	// <code>update:environment_feature_flags</code>
	// </div>.
	//
	// PATCH /api/v1/environment/feature_flags/{feature_flag_key}
	UpdateEnvironementFeatureFlagOverride(ctx context.Context, req *UpdateEnvironementFeatureFlagOverrideReq, params UpdateEnvironementFeatureFlagOverrideParams) (UpdateEnvironementFeatureFlagOverrideRes, error)
	// UpdateEnvironmentVariable implements updateEnvironmentVariable operation.
	//
	// Update an environment variable you previously created. This feature is in beta and admin UI is not
	// yet available.
	// <div>
	// <code>update:environment_variables</code>
	// </div>.
	//
	// PATCH /api/v1/environment_variables/{variable_id}
	UpdateEnvironmentVariable(ctx context.Context, req *UpdateEnvironmentVariableReq, params UpdateEnvironmentVariableParams) (UpdateEnvironmentVariableRes, error)
	// UpdateFeatureFlag implements UpdateFeatureFlag operation.
	//
	// Update feature flag.
	// <div>
	// <code>update:feature_flags</code>
	// </div>.
	//
	// PUT /api/v1/feature_flags/{feature_flag_key}
	UpdateFeatureFlag(ctx context.Context, params UpdateFeatureFlagParams) (UpdateFeatureFlagRes, error)
	// UpdateIdentity implements UpdateIdentity operation.
	//
	// Update identity by ID.
	// <div>
	// <code>update:identities</code>
	// </div>.
	//
	// PATCH /api/v1/identities/{identity_id}
	UpdateIdentity(ctx context.Context, req *UpdateIdentityReq, params UpdateIdentityParams) (UpdateIdentityRes, error)
	// UpdateOrganization implements updateOrganization operation.
	//
	// Update an organization.
	// <div>
	// <code>update:organizations</code>
	// </div>.
	//
	// PATCH /api/v1/organization/{org_code}
	UpdateOrganization(ctx context.Context, req OptUpdateOrganizationReq, params UpdateOrganizationParams) (UpdateOrganizationRes, error)
	// UpdateOrganizationFeatureFlagOverride implements UpdateOrganizationFeatureFlagOverride operation.
	//
	// Update organization feature flag override.
	// <div>
	// <code>update:organization_feature_flags</code>
	// </div>.
	//
	// PATCH /api/v1/organizations/{org_code}/feature_flags/{feature_flag_key}
	UpdateOrganizationFeatureFlagOverride(ctx context.Context, params UpdateOrganizationFeatureFlagOverrideParams) (UpdateOrganizationFeatureFlagOverrideRes, error)
	// UpdateOrganizationProperties implements UpdateOrganizationProperties operation.
	//
	// Update organization property values.
	// <div>
	// <code>update:organization_properties</code>
	// </div>.
	//
	// PATCH /api/v1/organizations/{org_code}/properties
	UpdateOrganizationProperties(ctx context.Context, req *UpdateOrganizationPropertiesReq, params UpdateOrganizationPropertiesParams) (UpdateOrganizationPropertiesRes, error)
	// UpdateOrganizationProperty implements UpdateOrganizationProperty operation.
	//
	// Update organization property value.
	// <div>
	// <code>update:organization_properties</code>
	// </div>.
	//
	// PUT /api/v1/organizations/{org_code}/properties/{property_key}
	UpdateOrganizationProperty(ctx context.Context, params UpdateOrganizationPropertyParams) (UpdateOrganizationPropertyRes, error)
	// UpdateOrganizationSessions implements UpdateOrganizationSessions operation.
	//
	// Update the organization's session configuration.
	// <div>
	// <code>update:organizations</code>
	// </div>.
	//
	// PATCH /api/v1/organizations/{org_code}/sessions
	UpdateOrganizationSessions(ctx context.Context, req *UpdateOrganizationSessionsReq, params UpdateOrganizationSessionsParams) (UpdateOrganizationSessionsRes, error)
	// UpdateOrganizationUsers implements UpdateOrganizationUsers operation.
	//
	// Update users that belong to an organization.
	// <div>
	// <code>update:organization_users</code>
	// </div>.
	//
	// PATCH /api/v1/organizations/{org_code}/users
	UpdateOrganizationUsers(ctx context.Context, req OptUpdateOrganizationUsersReq, params UpdateOrganizationUsersParams) (UpdateOrganizationUsersRes, error)
	// UpdatePermissions implements UpdatePermissions operation.
	//
	// Update permission
	// <div>
	// <code>update:permissions</code>
	// </div>.
	//
	// PATCH /api/v1/permissions/{permission_id}
	UpdatePermissions(ctx context.Context, req OptUpdatePermissionsReq, params UpdatePermissionsParams) (UpdatePermissionsRes, error)
	// UpdateProperty implements UpdateProperty operation.
	//
	// Update property.
	// <div>
	// <code>update:properties</code>
	// </div>.
	//
	// PUT /api/v1/properties/{property_id}
	UpdateProperty(ctx context.Context, req *UpdatePropertyReq, params UpdatePropertyParams) (UpdatePropertyRes, error)
	// UpdateRolePermissions implements UpdateRolePermissions operation.
	//
	// Update role permissions.
	// <div>
	// <code>update:role_permissions</code>
	// </div>.
	//
	// PATCH /api/v1/roles/{role_id}/permissions
	UpdateRolePermissions(ctx context.Context, req *UpdateRolePermissionsReq, params UpdateRolePermissionsParams) (UpdateRolePermissionsRes, error)
	// UpdateRoles implements UpdateRoles operation.
	//
	// Update a role
	// <div>
	// <code>update:roles</code>
	// </div>.
	//
	// PATCH /api/v1/roles/{role_id}
	UpdateRoles(ctx context.Context, req OptUpdateRolesReq, params UpdateRolesParams) (UpdateRolesRes, error)
	// UpdateUser implements updateUser operation.
	//
	// Update a user record.
	// <div>
	// <code>update:users</code>
	// </div>.
	//
	// PATCH /api/v1/user
	UpdateUser(ctx context.Context, req *UpdateUserReq, params UpdateUserParams) (UpdateUserRes, error)
	// UpdateUserFeatureFlagOverride implements UpdateUserFeatureFlagOverride operation.
	//
	// Update user feature flag override.
	// <div>
	// <code>update:user_feature_flags</code>
	// </div>.
	//
	// PATCH /api/v1/users/{user_id}/feature_flags/{feature_flag_key}
	UpdateUserFeatureFlagOverride(ctx context.Context, params UpdateUserFeatureFlagOverrideParams) (UpdateUserFeatureFlagOverrideRes, error)
	// UpdateUserProperties implements UpdateUserProperties operation.
	//
	// Update property values.
	// <div>
	// <code>update:user_properties</code>
	// </div>.
	//
	// PATCH /api/v1/users/{user_id}/properties
	UpdateUserProperties(ctx context.Context, req *UpdateUserPropertiesReq, params UpdateUserPropertiesParams) (UpdateUserPropertiesRes, error)
	// UpdateUserProperty implements UpdateUserProperty operation.
	//
	// Update property value.
	// <div>
	// <code>update:user_properties</code>
	// </div>.
	//
	// PUT /api/v1/users/{user_id}/properties/{property_key}
	UpdateUserProperty(ctx context.Context, params UpdateUserPropertyParams) (UpdateUserPropertyRes, error)
	// UpdateWebHook implements UpdateWebHook operation.
	//
	// Update a webhook
	// <div>
	// <code>update:webhooks</code>
	// </div>.
	//
	// PATCH /api/v1/webhooks/{webhook_id}
	UpdateWebHook(ctx context.Context, req *UpdateWebHookReq, params UpdateWebHookParams) (UpdateWebHookRes, error)
	// VerifyApiKey implements verifyApiKey operation.
	//
	// Verify an API key (public endpoint, no authentication required).
	//
	// POST /api/v1/api_keys/verify
	VerifyApiKey(ctx context.Context, req *VerifyApiKeyReq) (VerifyApiKeyRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
